- Modules/qSystems/DataTypes/Table.lua
Added support so we can load this in modules as shown above. Moved GetIndexByValue here.
I want to basically add functions to the preexisting table functions with this module, instead of making a new syntax ("Table.copy" < "table.copy").
*Also, please change the name of the module to "table"*
> Extend table library! table = LoadCustomLibrary("table")

- Modules/Utility/HashProcessor.lua
Changed RenderStepped to Heartbeat because the hash processor is not dependant on frame rate.
Please refer to the following article:
http://devforum.roblox.com/t/runservice-heartbeat-switching-to-variable-frequency/23509
> Update HashProcessor for upcoming ROBLOX API changes

- Modules/Utility/os.lua
I clearly check on this code every so often, because I wrote it, and it needs to be functioning optimally. This pull request makes it so the module only generates the string tables a single time, and doesn't generate new tables for each use.
> Finish os.lua

- .github/CONTRIBUTING.md
- Doc/Examples/SnackbarClientMain.lua
- Doc/Manual/02_usage.md
Some areas of the code were still using `NevermoreEngine` as the module name in ReplicatedStorage when it should have been using just `Nevermore`.
> Fixing inconsistencies in requiring

- Modules/Shared/Utility/heartbeatWait.lua
\>= would mean the while loop never actually runs unless the waitTime is a very small number. Fixed by replacing with <
> Fixed heartbeatWait.lua

- src/binder/README.md
- src/binder/package-lock.json
- src/binder/src/Shared/Binder.lua
- src/brio/README.md
- src/brio/src/Shared/BrioUtils.lua
- src/brio/src/Shared/BrioUtils.spec.lua
- src/brio/src/Shared/RxBrioUtils.lua
- src/brio/src/Shared/RxBrioUtils.spec.lua
- src/instanceutils/src/Shared/RxInstanceUtils.lua
- src/instanceutils/src/Shared/RxInstanceUtils.spec.lua
- src/rx/src/Shared/Rx.lua
- src/rx/src/Shared/Rx.spec.lua
<details>
<br />
```bash
npm install @quenty/actionmanager@3.2.0-canary.221.e58a344.0
npm install @quenty/attributeutils@3.3.0-canary.221.e58a344.0
npm install @quenty/binder@4.2.0-canary.221.e58a344.0
npm install @quenty/boundlinkutils@4.2.0-canary.221.e58a344.0
npm install @quenty/brio@3.2.0-canary.221.e58a344.0
npm install @quenty/cooldown@1.2.0-canary.221.e58a344.0
npm install @quenty/depthoffield@1.2.0-canary.221.e58a344.0
npm install @quenty/equippedtracker@3.2.0-canary.221.e58a344.0
npm install @quenty/hide@1.2.0-canary.221.e58a344.0
npm install @quenty/humanoidspeed@1.2.0-canary.221.e58a344.0
npm install @quenty/humanoidtracker@3.2.0-canary.221.e58a344.0
npm …
```
> feat: Add unit tests and other small features

- src/cmdrservice/package.json
- src/cmdrservice/src/Client/CmdrServiceClient.lua
- src/cmdrservice/src/Server/CmdrService.lua
- src/cmdrservice/src/Server/CmdrTemplateProviderServer/CmdrCommandDefinitionTemplate.lua
- src/cmdrservice/src/Server/CmdrTemplateProviderServer/CmdrExecutionTemplate.lua
- src/cmdrservice/src/Server/CmdrTemplateProviderServer/init.lua
- src/cmdrservice/test/default.project.json
- src/cmdrservice/test/scripts/Server/ServerMain.server.lua
<details>
<br />
```bash
npm install @quenty/cmdrservice@3.4.0-canary.231.1897e2a.0
yarn add @quenty/cmdrservice@3.4.0-canary.231.1897e2a.0
```
</details>
> feat: Make CmdrService allow dynamically binding commands

- src/guivisiblemanager/src/Client/GuiVisibleManager.lua
<details>
<br />
```bash
npm install @quenty/guivisiblemanager@4.0.0-canary.236.5d9a2f6.0
yarn add @quenty/guivisiblemanager@4.0.0-canary.236.5d9a2f6.0
```
</details>
> feat!: Remove GuiVisibleManager:SetPreferredTheme() support

- src/draw/src/Shared/Draw.lua
Parts created in draw module shouldn't interfere with anything, therefore I thought CanTouch and CanQuery should also be false.
> fix: Disabled CanTouch and CanQuery

- LICENSE.md
- moonwave.toml
Edits made in both [`moonwave.toml`](https://github.com/insyri/NevermoreEngine/commit/ab017723092e2a90014274f854177dbf66e33da4) and [`LICENSE.md`](https://github.com/insyri/NevermoreEngine/commit/2649fef8c1fadc1e4523958cc72e6392ae9ab6c0).
2021 -> 2022
> Bump license/copyright date

- src/maid/src/Shared/Maid.lua
- src/maid/src/Shared/MaidTaskUtils.lua
Maids should call `task.cancel` on jobs it's given that are threads.
> feat: Add thread-support for maids

- src/qframe/src/Shared/QFrame.lua
`QFrame.isNaN` returns the opposite boolean that it should. This fixes that.
> fix: Fix QFrame.isNaN

- src/quaternion/src/Shared/Quaternion.lua
It appears `SlerpQuaternions` was intended to follow either the first or fourth of the following equivalent equations, but the order of the arguments to one of the Qmul calls was switched.
[https://en.wikipedia.org/wiki/Slerp#Quaternion_Slerp](https://en.wikipedia.org/wiki/Slerp#Quaternion_Slerp)
I chose to convert it to the fourth equation.
> Fix SlerpQuaternions

- src/resetservice/src/Client/ResetServiceClient.lua
`ResetServiceClient:_promiseRemoteEvent()` is actually indexing a property from `self`, which isn't passed when you call a metatable's method with a `.`, you have to use `:` to pass on `self`.
> Fix: Corrected method call

- tools/nevermore-cli/package-lock.json
- tools/nevermore-cli/templates/game-template/.github/workflows/build.yml
- tools/nevermore-cli/templates/game-template/aftman.toml
<details>
<br />
```bash
npm install @quenty/nevermore-cli@1.5.0-canary.329.8369044.0
yarn add @quenty/nevermore-cli@1.5.0-canary.329.8369044.0
```
</details>
> feat: Add github workflow to nevermore init command

- src/screenshothudservice/README.md
- src/screenshothudservice/default.project.json
- src/screenshothudservice/package.json
- src/screenshothudservice/src/Client/ScreenshotHudModel.lua
- src/screenshothudservice/src/Client/ScreenshotHudServiceClient.lua
- src/screenshothudservice/src/node_modules.project.json
- src/screenshothudservice/test/default.project.json
- src/screenshothudservice/test/scripts/Client/ClientMain.client.lua
- src/screenshothudservice/test/scripts/Server/ServerMain.server.lua
<details>
<br />
```bash
npm install @quenty/screenshothudservice@1.1.0-canary.333.1160373.0
yarn add @quenty/screenshothudservice@1.1.0-canary.333.1160373.0
```
</details>
> feat: Add ScreenshotHudService which allows the screenshot HUD to be manipulated

- src/flipbook/src/Client/Flipbook.lua
- src/flipbook/src/Client/Player/FlipbookPlayer.story.lua
<details>
<br />
```bash
npm install @quenty/flipbook@2.0.2-canary.340.fc60b33.0
yarn add @quenty/flipbook@2.0.2-canary.340.fc60b33.0
```
</details>
> fix: Fix flipbook playback on odd row/column scenarios

- src/clienttranslator/src/Client/JSONTranslator.lua
- src/softshutdown/src/Client/SoftShutdownServiceClient.lua
- src/softshutdown/src/Client/SoftShutdownUI.story.lua
<details>
<br />
```bash
npm install @quenty/clienttranslator@8.13.1-canary.342.ee93043.0
npm install @quenty/gameconfig@5.17.1-canary.342.ee93043.0
npm install @quenty/gameproductservice@6.3.1-canary.342.ee93043.0
npm install @quenty/inputkeymaputils@7.17.1-canary.342.ee93043.0
npm install @quenty/scoredactionservice@9.17.1-canary.342.ee93043.0
npm install @quenty/settings-inputkeymap@3.19.1-canary.342.ee93043.0
npm install @quenty/softshutdown@3.18.2-canary.342.ee93043.0
yarn add @quenty/clienttranslator@8.13.1-canary.342.ee93043.0
yarn add @quenty/gameconfig@5.17.1-canary.342.ee93043.0
yarn add @quenty/gameproductservice@6.3.1-canary.342.ee93043.0
yarn add …
```
> fix: Fix localization not swapping in soft shutdown if locale swaps

- src/gameproductservice/package.json
<details>
<br />
```bash
npm install @quenty/gameproductservice@7.1.1-canary.355.d6e5583.0
yarn add @quenty/gameproductservice@7.1.1-canary.355.d6e5583.0
```
</details>
> fix: Fix missing dependency in gameproductservice

- src/influxdbclient/src/Server/Config/InfluxDBWriteOptionUtils.lua
<details>
<br />
```bash
npm install @quenty/influxdbclient@1.5.0-canary.361.518a7ca.0
yarn add @quenty/influxdbclient@1.5.0-canary.361.518a7ca.0
```
</details>
> feat: Increase default flush time which will decrease RPS for InfluxDB

- src/richtext/package.json
- src/richtext/src/Shared/RichTextUtils.lua
<details>
<br />
```bash
npm install @quenty/richtext@1.2.0-canary.364.ed790cd.0
yarn add @quenty/richtext@1.2.0-canary.364.ed790cd.0
```
</details>
> feat: Remove loader dependency requirement

- src/resetservice/src/Server/ResetService.lua
<details>
<br />
```bash
npm install @quenty/resetservice@5.7.1-canary.366.fac28fa.0
yarn add @quenty/resetservice@5.7.1-canary.366.fac28fa.0
```
</details>
> fix: Player can try to reset while not in game

- src/binder/src/Shared/Binder.lua
<details>
<br />
```bash
npm install @quenty/binder@8.18.1-canary.375.36f3417.0
npm install @quenty/boundlinkutils@8.18.1-canary.375.36f3417.0
npm install @quenty/cooldown@5.23.1-canary.375.36f3417.0
npm install @quenty/deathreport@3.21.1-canary.375.36f3417.0
npm install @quenty/gameconfig@5.29.1-canary.375.36f3417.0
npm install @quenty/gameproductservice@7.7.1-canary.375.36f3417.0
npm install @quenty/hide@5.20.1-canary.375.36f3417.0
npm install @quenty/humanoidspeed@5.23.1-canary.375.36f3417.0
npm install @quenty/idleservice@7.27.2-canary.375.36f3417.0
npm install @quenty/ik@9.28.2-canary.375.36f3417.0
npm install @quenty/motor6d@1.24.1-canary.375.36f3417.0
npm …
```
> fix: Fix binder args failing in no-arg non-service-provided interface

- src/octree/src/Shared/Octree.lua
Updated the word "upating" to "updating" in the main documentation comment in Octree.lua
> Fixed documentation typo in Octree.lua

- src/datastore/src/Shared/Utility/DataStoreStringUtils.lua
[Example 2.b](https://gist.github.com/TheGreatSageEqualToHeaven/e0e1dc2698307c93f6013b9825705899#example-2b)
> Fix `DataStoreStringUtils.isValidUTF8` not detecting invalid strings

- src/datastore/src/Shared/Utility/DataStoreStringUtils.lua
<details>
<br />
```bash
npm install @quenty/datastore@7.25.1-canary.409.ed39424.0
npm install @quenty/secrets@1.18.1-canary.409.ed39424.0
npm install @quenty/settings-inputkeymap@3.41.1-canary.409.ed39424.0
npm install @quenty/settings@4.37.1-canary.409.ed39424.0
npm install @quenty/softshutdown@3.40.1-canary.409.ed39424.0
yarn add @quenty/datastore@7.25.1-canary.409.ed39424.0
yarn add @quenty/secrets@1.18.1-canary.409.ed39424.0
yarn add @quenty/settings-inputkeymap@3.41.1-canary.409.ed39424.0
yarn add @quenty/settings@4.37.1-canary.409.ed39424.0
yarn add @quenty/softshutdown@3.40.1-canary.409.ed39424.0
```
</details>
> fix: Fix actual code for data store match

- src/datastore/src/Server/Modules/DataStoreWriter.lua
<details>
<br />
```bash
npm install @quenty/datastore@7.26.1-canary.413.3303b36.0
npm install @quenty/secrets@1.20.1-canary.413.3303b36.0
npm install @quenty/settings-inputkeymap@3.43.1-canary.413.3303b36.0
npm install @quenty/settings@4.39.1-canary.413.3303b36.0
npm install @quenty/softshutdown@3.41.1-canary.413.3303b36.0
yarn add @quenty/datastore@7.26.1-canary.413.3303b36.0
yarn add @quenty/secrets@1.20.1-canary.413.3303b36.0
yarn add @quenty/settings-inputkeymap@3.43.1-canary.413.3303b36.0
yarn add @quenty/settings@4.39.1-canary.413.3303b36.0
yarn add @quenty/softshutdown@3.41.1-canary.413.3303b36.0
```
</details>
> fix: Fix datastore writer copying non-table scenario

- src/datastore/src/Server/Modules/DataStoreStage.lua
<details>
<br />
```bash
npm install @quenty/datastore@8.0.1-canary.420.2ec98e4.0
npm install @quenty/secrets@2.0.2-canary.420.2ec98e4.0
npm install @quenty/settings-inputkeymap@4.2.1-canary.420.2ec98e4.0
npm install @quenty/settings@5.1.1-canary.420.2ec98e4.0
npm install @quenty/softshutdown@4.0.1-canary.420.2ec98e4.0
yarn add @quenty/datastore@8.0.1-canary.420.2ec98e4.0
yarn add @quenty/secrets@2.0.2-canary.420.2ec98e4.0
yarn add @quenty/settings-inputkeymap@4.2.1-canary.420.2ec98e4.0
yarn add @quenty/settings@5.1.1-canary.420.2ec98e4.0
yarn add @quenty/softshutdown@4.0.1-canary.420.2ec98e4.0
```
</details>
> fix: Fix retrieving key set from datastore

- src/singleton/src/Shared/Singleton.lua
This should make it play nicer with things like InputModeTypeSelectors.
> fix: Singleton uses rawget/rawset to query stuff

- src/animations/src/Shared/AnimationPromiseUtils.lua
- src/animations/src/Shared/AnimationTrackPlayer.lua
<details>
<br />
```bash
npm install @quenty/actionmanager@12.1.0-canary.447.5f743bf.0
npm install @quenty/adorneeboundingbox@7.1.0-canary.447.5f743bf.0
npm install @quenty/adorneedata@6.1.0-canary.447.5f743bf.0
npm install @quenty/adorneevalue@9.1.0-canary.447.5f743bf.0
npm install @quenty/animationgroup@9.1.0-canary.447.5f743bf.0
npm install @quenty/animationprovider@10.1.0-canary.447.5f743bf.0
npm install @quenty/animations@6.1.0-canary.447.5f743bf.0
npm install @quenty/applytagtotaggedchildren@9.1.0-canary.447.5f743bf.0
npm install @quenty/assetserviceutils@4.1.0-canary.447.5f743bf.0
npm install @quenty/attributeutils@13.1.0-canary.447.5f743bf.0
npm install …
```
> feat: Add AnimationPromiseUtils.promiseLoaded(animationTrack) and other helper calls

- src/humanoidspeed/src/Server/HumanoidSpeed.lua
- src/rogue-humanoid/src/Shared/RogueHumanoidBase.lua
- src/rogue-properties/src/Shared/Implementation/RogueProperty.lua
- src/rogue-properties/src/Shared/Modifiers/Additive/RogueAdditiveProvider.lua
- src/rogue-properties/src/Shared/Modifiers/Multiplier/RogueMultiplierProvider.lua
<details>
<br />
```bash
npm install @quenty/humanoidspeed@11.0.1-canary.451.ee93033.0
npm install @quenty/rogue-humanoid@9.0.1-canary.451.ee93033.0
npm install @quenty/rogue-properties@10.0.1-canary.451.ee93033.0
yarn add @quenty/humanoidspeed@11.0.1-canary.451.ee93033.0
yarn add @quenty/rogue-humanoid@9.0.1-canary.451.ee93033.0
yarn add @quenty/rogue-properties@10.0.1-canary.451.ee93033.0
```
</details>
> fix: Fix rogue properties 

- src/datastore/src/Server/PrivateServerDataStoreService.lua
<details>
<br />
```bash
npm install @quenty/chatproviderservice@9.2.0-canary.455.45dc12d.0
npm install @quenty/datastore@13.2.0-canary.455.45dc12d.0
npm install @quenty/secrets@7.2.0-canary.455.45dc12d.0
npm install @quenty/settings@11.2.0-canary.455.45dc12d.0
npm install @quenty/settings-inputkeymap@10.2.0-canary.455.45dc12d.0
npm install @quenty/softshutdown@9.2.0-canary.455.45dc12d.0
yarn add @quenty/chatproviderservice@9.2.0-canary.455.45dc12d.0
yarn add @quenty/datastore@13.2.0-canary.455.45dc12d.0
yarn add @quenty/secrets@7.2.0-canary.455.45dc12d.0
yarn add @quenty/settings@11.2.0-canary.455.45dc12d.0
yarn add …
```
> feat: custom key for private server datastore

- src/randomutils/src/Shared/RandomUtils.lua
If the passed chances array starts with a zero, the first element will be be picked if `math.random() == 0`, as the function returns [0,1). An element with a weight of zero should never be picked.
> fix: RandomUtils.weightedChoice when chances array starts with 0(s)

- src/buttonhighlightmodel/src/Client/ButtonHighlightModel.lua
ButtonHighlightModel has a method for observing the highlighted target `:ObservePercentHighlightedTarget()` but not one for observing the pressed, or selected targets.
> fix: Add missing ObservePercentTarget methods

- src/inputkeymaputils/src/Shared/Types/SlottedTouchButtonUtils.lua
<details>
<br />
```bash
npm install @quenty/inputkeymaputils@14.6.0-canary.473.55c4529.0
npm install @quenty/scoredactionservice@16.7.0-canary.473.55c4529.0
npm install @quenty/settings-inputkeymap@10.8.0-canary.473.55c4529.0
yarn add @quenty/inputkeymaputils@14.6.0-canary.473.55c4529.0
yarn add @quenty/scoredactionservice@16.7.0-canary.473.55c4529.0
yarn add @quenty/settings-inputkeymap@10.8.0-canary.473.55c4529.0
```
</details>
> feat: Add slotIds for priority1 and priority2 buttons

- src/inputkeymaputils/src/Shared/Types/SlottedTouchButtonUtils.lua
<details>
<br />
```bash
npm install @quenty/inputkeymaputils@14.5.1-canary.474.daf1700.0
npm install @quenty/scoredactionservice@16.6.1-canary.474.daf1700.0
npm install @quenty/settings-inputkeymap@10.7.1-canary.474.daf1700.0
yarn add @quenty/inputkeymaputils@14.5.1-canary.474.daf1700.0
yarn add @quenty/scoredactionservice@16.6.1-canary.474.daf1700.0
yarn add @quenty/settings-inputkeymap@10.7.1-canary.474.daf1700.0
```
</details>
> fix: Rename priority1 & priority2 -> primary4 & primary5

- src/viewport/src/Client/Viewport.lua
- src/viewport/src/Client/ViewportControls.lua
* Adds API to allow consumers to disable / enable both `ViewportControl` instance, and `Viewport` instances
> feat[Viewport]: Added ability to disable ViewportControls

- docs/install.md
Added missing information about the bootstrapping process on the client.
> Docs: Update installation docs to include info on new loader

- src/camera/src/Client/Controls/CameraControls.lua
Unbinding a CAS action emits `Enum.UserInputType.None`. This breaks destruction in the enabled state.
> fix: CameraControls destruction in Enabled state

- src/observablecollection/src/Shared/ObservableMap.lua
The maid is given some cleanup w/ `:GiveTask`, so they get given keys `1` and `2` internally. The value brios are also put into this maid, so if you did `map:Set(1, ...)` you'd break everything observing the container.
> fix: Using integer keys in w/ Observe methods in ObservableMap

- plugins/ui-converter-plugin/src/modules/Server/UIConverter.lua
- plugins/ui-converter-plugin/src/modules/Server/UIConverterUtils.lua
- src/roblox-api-dump/src/Server/RobloxApiMember.lua
There were new properties "Capabilities" and "Sandboxed" that were recently added to the `Instance` class, so this change adds a method to `RobloxApiMember.lua` in the `roblox-api-dump` package, which lets us check the permission for these properties. This will fix the plugin erroring when you attempt to convert instances.
<details>
<br />
```bash
npm install @quenty/roblox-api-dump@8.3.1-canary.485.6fcadf5.0
yarn add @quenty/roblox-api-dump@8.3.1-canary.485.6fcadf5.0
```
</details>
> fix: Fix Blend converter plugin erroring

- tools/nevermore-cli/templates/game-template/.editorconfig
This PR corrects a couple of typos in the `.editorconfig` file of the game template.
According to the [EditorConfig spec](https://spec.editorconfig.org/index.html#supported-pairs):
- The key `indent_width` should be `indent_size`
- The value of `indent_style`, previously set to `spaces` (plural), should be `space` (singular).
> Update .editorconfig keys from game template

- tools/nevermore-cli/templates/plugin-template/default.project.json
With the `default.project.json` included by `nevermore init-plugin`, Rojo cannot properly build the plugin. In its current state, the resulting plugin file will be missing the code. These changes should fix that.
> fix: Fix plugin template to fix Rojo build issues

- aftman.toml
- games/integration/aftman.toml
- src/blend/src/Shared/Blend/SpringObject.lua
- src/servicebag/src/Shared/ServiceBag.lua
- src/uiobjectutils/src/Client/GuiInteractionUtils.lua
- tools/nevermore-cli/templates/game-template/aftman.toml
Before the spring object would initialize with a number in Blend.Spring() if the initial observable emitted late, but speed or some other property changed. Now we delay emission until the first real type is made, so we don't swap types to a number when setting speed.
Querying the spring object will still result in the default number and value.
<details>
<br />
```bash
npm install @quenty/adorneeboundingbox@8.5.1-canary.496.cb49bdf.0
npm install @quenty/adorneevalue@10.5.1-canary.496.cb49bdf.0
npm install @quenty/blend@12.5.1-canary.496.cb49bdf.0
npm install @quenty/bodycolorsutils@7.5.1-canary.496.cb49bdf.0
npm install …
```
> fix: Spring object initializes properly

- src/snackbar/package.json
Set dependency version for @quentystudios/t to ^3.0.0 in src/snackbar/package.json. This fixes the following error while installing @quenty/snackbar:
`npm ERR! code ETARGET
npm ERR! notarget No matching version found for @quentystudios/t@^3.0.1.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.`
> fix: No matching version found for @quentystudios/t@^3.0.1 while installing @quenty/snackbar

- src/loader/src/Maid.lua
fixes https://github.com/Quenty/NevermoreEngine/issues/286, fixes https://github.com/Quenty/NevermoreEngine/issues/397
> docs: Fix duplicate entries on docs [skip ci]

- src/qgui/src/Shared/qGUI.lua
- src/ragdoll/src/Client/RagdollBindersClient.lua
- src/ragdoll/src/Server/RagdollBindersServer.lua
- src/steputils/src/Shared/StepUtils.lua
<details>
<br />
```bash
npm install @quenty/actionmanager@13.9.1-canary.506.9cbf2c1.0
npm install @quenty/adorneeboundingbox@8.9.1-canary.506.9cbf2c1.0
npm install @quenty/adorneedata@7.10.1-canary.506.9cbf2c1.0
npm install @quenty/adorneevalue@10.9.1-canary.506.9cbf2c1.0
npm install @quenty/animationprovider@11.7.1-canary.506.9cbf2c1.0
npm install @quenty/animations@8.9.1-canary.506.9cbf2c1.0
npm install @quenty/assetserviceutils@5.11.1-canary.506.9cbf2c1.0
npm install @quenty/attributeutils@14.9.1-canary.506.9cbf2c1.0
npm install @quenty/avatareditorutils@7.10.1-canary.506.9cbf2c1.0
npm install @quenty/basicpane@13.9.1-canary.506.9cbf2c1.0
npm install …
```
> fix: Deprecate some signal APIs and qGUI

- src/tie/src/Shared/TieDefinition.lua
<details>
<br />
```bash
npm install @quenty/conditions@10.12.1-canary.514.c328cc1.0
npm install @quenty/gameproductservice@14.14.1-canary.514.c328cc1.0
npm install @quenty/humanoidspeed@12.12.1-canary.514.c328cc1.0
npm install @quenty/idleservice@13.13.1-canary.514.c328cc1.0
npm install @quenty/ik@15.14.1-canary.514.c328cc1.0
npm install @quenty/motor6d@7.12.1-canary.514.c328cc1.0
npm install @quenty/racketingropeconstraint@12.12.1-canary.514.c328cc1.0
npm install @quenty/ragdoll@15.13.1-canary.514.c328cc1.0
npm install @quenty/rogue-humanoid@10.12.1-canary.514.c328cc1.0
npm install @quenty/rogue-properties@11.12.1-canary.514.c328cc1.0
npm install …
```
> fix: Fix docs build

- src/cmdrservice/src/Server/CmdrTemplateProviderServer/CmdrExecutionTemplate.lua
- src/loader/src/Maid.lua
- src/quaternion/src/Shared/QuaternionObject.lua
- src/servicebag/src/Shared/ServiceBag.lua
- src/signal/src/Shared/GoodSignal.lua
- src/tie/src/Shared/TieDefinition.lua
<details>
<br />
```bash
npm install @quenty/accessorytypeutils@1.4.1-canary.508.0dab55e.0
npm install @quenty/actionmanager@13.9.2-canary.508.0dab55e.0
npm install @quenty/adorneeboundingbox@8.9.2-canary.508.0dab55e.0
npm install @quenty/adorneedata@7.10.2-canary.508.0dab55e.0
npm install @quenty/adorneevalue@10.9.2-canary.508.0dab55e.0
npm install @quenty/animationgroup@10.7.1-canary.508.0dab55e.0
npm install @quenty/animationprovider@11.7.2-canary.508.0dab55e.0
npm install @quenty/animations@8.9.2-canary.508.0dab55e.0
npm install @quenty/applytagtotaggedchildren@10.7.1-canary.508.0dab55e.0
npm install @quenty/assetserviceutils@5.11.2-canary.508.0dab55e.0
npm …
```
> docs: Fix serviceBag init and other documentation errors

- .github/workflows/lint.yml
- src/numbersequenceutils/src/Shared/NumberSequenceUtils.lua
- tools/nevermore-cli/templates/game-template/.github/workflows/build.yml
<details>
<br />
```bash
npm install @quenty/numbersequenceutils@8.7.2-canary.526.61e0ac8.0
npm install @quenty/particles@5.7.2-canary.526.61e0ac8.0
npm install @quenty/nevermore-cli@4.4.2-canary.526.61e0ac8.0
yarn add @quenty/numbersequenceutils@8.7.2-canary.526.61e0ac8.0
yarn add @quenty/particles@5.7.2-canary.526.61e0ac8.0
yarn add @quenty/nevermore-cli@4.4.2-canary.526.61e0ac8.0
```
</details>
> feat: Add NumberSequenceUtils.scaleTransparency(sequence, scale)

- src/modelappearance/src/Shared/ModelAppearance.lua
<details>
<br />
```bash
npm install @quenty/modelappearance@10.7.2-canary.528.6a7533e.0
yarn add @quenty/modelappearance@10.7.2-canary.528.6a7533e.0
```
</details>
> fix: Support part operations in ModelAppearance API

- src/scoredactionservice/src/Client/Picker/ScoredActionPicker.lua
This change improves the behavior of the action picker by returning the first valid preferred action from the list, instead of just setting the first one in the table. The behavior can be observed when there are multiple actions within range.
<details>
<br />
```bash
npm install @quenty/scoredactionservice@16.22.1-canary.529.b027236.0
yarn add @quenty/scoredactionservice@16.22.1-canary.529.b027236.0
```
</details>
> fix: Set the first valid preferred action from the list

- src/camera/src/Client/Controls/CameraControls.lua
The function `CameraControls:SetVelocityStrength()` exists, but the variable that is set isn't applied anywhere - this change fixes that and applies to `SmoothRotatedCamera`.
> fix: Apply strength to camera controls

- src/rx/src/Shared/Rx.lua
Maid was getting an additional argument that should have been passed into the subscribe arguments, causing some operators to not emit on completion.
> fix: Typo causing some operators to not emit on source completion

- src/rogue-properties/src/Shared/Implementation/RoguePropertyTable.lua
__index function checks if index is a number to do work, assertion prevents this from happening by only allowing strings.
> fix: correct type assertion for index in RoguePropertyTable __index function

- src/datastore/package.json
- src/datastore/src/Server/Utility/DataStorePromises.lua
https://devforum.roblox.com/t/ordereddatastore-pages-object-is-never-isfinished-resulting-in-finite-loops-when-n-0/3558372
<details>
<br />
```bash
npm install @quenty/chatproviderservice@9.24.1-canary.543.25d35f7.0
npm install @quenty/datastore@13.19.1-canary.543.25d35f7.0
npm install @quenty/secrets@7.22.1-canary.543.25d35f7.0
npm install @quenty/settings@11.22.1-canary.543.25d35f7.0
npm install @quenty/settings-inputkeymap@10.24.1-canary.543.25d35f7.0
npm install @quenty/softshutdown@9.22.1-canary.543.25d35f7.0
yarn add @quenty/chatproviderservice@9.24.1-canary.543.25d35f7.0
yarn add @quenty/datastore@13.19.1-canary.543.25d35f7.0
yarn add …
```
> fix: Work around Roblox bug with OrderedDataStore never finishing
