Modules/Utility/os.lua, Modules/Utility/readme.md
Uses [these algorithms](http://howardhinnant.github.io/date_algorithms.html#weekday_from_days)
=> Improve os.date efficiency by another 12%

Install.lua
Makes installation a lot cooler
=> Add Loading Screen!

Modules/qGUI/PaperRipple/PaperRipple.lua
The parameters of the Vector2 need to be switched.
=> Fix TopRight, BottomLeft calculations

Modules/qGUI/PaperRipple/Ripple.lua
Top is old, bottom is new
It's might be difficult to see in this image, but in motion, there is an obvious difference. The top one has significantly darker edges.
=> Switch to an image with less harsh edge lines

Modules/Events/Maid.lua
Replaced all "disconnect"s with "Disconnect"
=> Replaced deprecated methods

Doc/Examples/SnackbarClientMain.lua
=> Fix typo in example

Install.lua
GitHub updated their website format, so here is the update!
=> Fix Install

Install.lua
=> Install doesn't install Submodules for the Loader

loader/ReplicatedStorage/Nevermore/README.md
=> Fixed misspelling

Modules/Server/DataStore/README.md
fixed, just felt like it was needed to be pointed out.
=> small typo on datastore documentation for datastore

Install.lua
Not proud of this code.... but I maintain it. So... here's your update. I believe this broke either yesterday or the day before.
=> Installer code update

default.project.json
Rojo 5 and Rojo 6 both use this new format
=> Update default.project.json according to new standard

Install.lua
tr classes were changed to spans.
=> Fix Installer

.github/FUNDING.yml
<details>
<br />
```bash
npm install @quenty/acceltween@1.0.3-canary.200.0a777f1.0
npm install @quenty/actionmanager@1.0.3-canary.200.0a777f1.0
npm install @quenty/adorneeutils@1.0.3-canary.200.0a777f1.0
npm install @quenty/animationgroup@1.0.3-canary.200.0a777f1.0
npm install @quenty/animationprovider@1.0.3-canary.200.0a777f1.0
npm install @quenty/animationtrackutils@1.0.3-canary.200.0a777f1.0
npm install @quenty/applytagtotaggedchildren@1.0.3-canary.200.0a777f1.0
npm install @quenty/attributeutils@1.0.3-canary.200.0a777f1.0
npm install @quenty/axisangleutils@1.0.3-canary.200.0a777f1.0
npm install @quenty/badgeutils@1.0.3-canary.200.0a777f1.0
npm install …
```
=> chore: Add funding links

src/attributeutils/src/Shared/AttributeValue.lua, src/binder/src/Shared/BinderProvider.lua, src/servicebag/src/Shared/ServiceBag.lua
<details>
<br />
```bash
npm install @quenty/attributeutils@3.3.1-canary.223.e74d841.0
npm install @quenty/binder@4.2.1-canary.223.e74d841.0
npm install @quenty/boundlinkutils@4.2.1-canary.223.e74d841.0
npm install @quenty/camera@4.2.4-canary.223.e74d841.0
npm install @quenty/cmdrservice@3.1.3-canary.223.e74d841.0
npm install @quenty/cooldown@1.2.1-canary.223.e74d841.0
npm install @quenty/hide@1.2.1-canary.223.e74d841.0
npm install @quenty/hintscoringutils@4.2.4-canary.223.e74d841.0
npm install @quenty/humanoidspeed@1.2.1-canary.223.e74d841.0
npm install @quenty/idleservice@1.3.1-canary.223.e74d841.0
npm install @quenty/ik@4.3.1-canary.223.e74d841.0
npm install …
```
=> fix: Minor fixes

src/resetservice/README.md, src/resetservice/default.project.json, src/resetservice/package-lock.json, src/resetservice/package.json, src/resetservice/src/Client/ResetServiceClient.lua, src/resetservice/src/Server/ResetService.lua, src/resetservice/src/Shared/ResetServiceConstants.lua, src/resetservice/src/node_modules.project.json, src/string/src/Shared/String.lua
<details>
<br />
```bash
npm install @quenty/animationprovider@3.3.0-canary.224.ceec2f8.0
npm install @quenty/attributeutils@3.4.0-canary.224.ceec2f8.0
npm install @quenty/binder@4.3.0-canary.224.ceec2f8.0
npm install @quenty/boundlinkutils@4.3.0-canary.224.ceec2f8.0
npm install @quenty/camera@4.3.0-canary.224.ceec2f8.0
npm install @quenty/cmdrservice@3.2.0-canary.224.ceec2f8.0
npm install @quenty/cooldown@1.3.0-canary.224.ceec2f8.0
npm install @quenty/generatewithmixin@3.3.0-canary.224.ceec2f8.0
npm install @quenty/genericscreenguiprovider@3.3.0-canary.224.ceec2f8.0
npm install @quenty/hide@1.3.0-canary.224.ceec2f8.0
npm install …
```
=> feat: Add reset service and some string utils

src/remotefunctionutils/src/Shared/RemoteFunctionUtils.lua
changed pack to unpack to fix bug where you got a table and not the arguments you requested
=> fix: RemoteFunctionUtils.promiseInvokeServer

src/grouputils/src/Shared/GroupUtils.lua
Added promiseRoleInGroup to GroupUtils
used promiseRankInGroup as example
=> feat: Added promiseRoleInGroup to GroupUtils

foreman.toml, src/animationprovider/src/Shared/AnimationProvider.lua, src/binder/src/Shared/Binder.lua, src/cooldown/src/Shared/CooldownBase.lua, src/servicebag/src/Shared/ServiceBag.lua
Adds a variety of small fixes to Nevermore. 
<details>
<br />
```bash
npm install @quenty/animationprovider@3.4.1-canary.230.6e7a84d.0
npm install @quenty/binder@4.3.1-canary.230.6e7a84d.0
npm install @quenty/boundlinkutils@4.3.1-canary.230.6e7a84d.0
npm install @quenty/camera@4.3.1-canary.230.6e7a84d.0
npm install @quenty/cmdrservice@3.2.1-canary.230.6e7a84d.0
npm install @quenty/cooldown@1.3.1-canary.230.6e7a84d.0
npm install @quenty/hide@1.3.1-canary.230.6e7a84d.0
npm install @quenty/hintscoringutils@4.3.1-canary.230.6e7a84d.0
npm install @quenty/humanoidspeed@1.3.1-canary.230.6e7a84d.0
npm install @quenty/idleservice@1.4.1-canary.230.6e7a84d.0
npm install …
```
=> fix: A variety of misc fixes for Nevermore

src/clienttranslator/src/Client/JSONTranslator.lua, src/clienttranslator/src/Shared/JsonToLocalizationTable.lua, src/cmdrservice/src/Client/CmdrServiceClient.lua
<details>
<br />
```bash
npm install @quenty/clienttranslator@4.3.0-canary.232.9e1e185.0
npm install @quenty/cmdrservice@3.5.0-canary.232.9e1e185.0
yarn add @quenty/clienttranslator@4.3.0-canary.232.9e1e185.0
yarn add @quenty/cmdrservice@3.5.0-canary.232.9e1e185.0
```
</details>
=> feat: Add translator and cmdr features

src/blend/README.md, src/blend/default.project.json, src/blend/package-lock.json, src/blend/package.json, src/blend/src/Client/Blend/Blend.lua, src/blend/src/Client/Blend/BlendDefaultProps.lua, src/blend/src/Client/Test/BlendChildren.story.lua, src/blend/src/Client/Test/BlendComputePairs.story.lua, src/blend/src/Client/Test/BlendPromise.story.lua, src/blend/src/Client/Test/BlendSpring.story.lua, src/blend/src/Client/Test/BlendTextbox.story.lua, src/blend/src/node_modules.project.json, src/blend/test/default.project.json, src/blend/test/scripts/Client/ClientMain.client.lua, src/blend/test/scripts/Server/ServerMain.server.lua, src/cooldown/package-lock.json, src/cooldown/package.json, src/cooldown/src/Client/CooldownTracker.lua, src/cooldown/src/Server/Cooldown.lua, src/cooldown/src/Shared/CooldownBase.lua, src/playerhumanoidbinder/src/Server/PlayerHumanoidBinder.lua, src/playerthumbnailutils/src/Shared/PlayerThumbnailUtils.lua, src/ragdoll/package-lock.json, src/ragdoll/package.json, src/ragdoll/src/Server/RagdollBindersServer.lua, src/rx/src/Shared/Subscription.lua, src/sounds/src/Shared/SoundUtils.lua, src/valuebaseutils/src/Shared/ValueBaseUtils.lua, src/valueobject/src/Shared/ValueObject.lua, src/valueobject/src/Shared/ValueObjectUtils.lua
<details>
<br />
```bash
npm install @quenty/actionmanager@3.3.1-canary.234.cb1f814.0
npm install @quenty/attributeutils@3.4.1-canary.234.cb1f814.0
npm install @quenty/binder@4.3.2-canary.234.cb1f814.0
npm install @quenty/blend@1.0.1-canary.234.cb1f814.0
npm install @quenty/boundlinkutils@4.3.2-canary.234.cb1f814.0
npm install @quenty/brio@3.3.1-canary.234.cb1f814.0
npm install @quenty/cooldown@1.3.2-canary.234.cb1f814.0
npm install @quenty/depthoffield@1.3.1-canary.234.cb1f814.0
npm install @quenty/equippedtracker@3.3.1-canary.234.cb1f814.0
npm install @quenty/hide@1.3.2-canary.234.cb1f814.0
npm install @quenty/humanoidspeed@1.3.2-canary.234.cb1f814.0
npm install …
```
=> feat: Add blend package and a variety of other changes

src/attributeutils/src/Shared/AttributeValue.lua, src/ragdoll/src/Server/Classes/UnragdollAutomatically.lua, src/ragdoll/src/Server/RagdollBindersServer.lua, src/spring/src/Shared/SpringUtils.lua, src/textserviceutils/package-lock.json, src/textserviceutils/package.json, src/textserviceutils/src/Shared/TextServiceUtils.lua, src/textserviceutils/src/node_modules.project.json
<details>
<br />
```bash
npm install @quenty/attributeutils@3.7.0-canary.237.7ab2e27.0
npm install @quenty/blend@1.3.0-canary.237.7ab2e27.0
npm install @quenty/camera@4.5.0-canary.237.7ab2e27.0
npm install @quenty/gamescalingutils@2.2.0-canary.237.7ab2e27.0
npm install @quenty/guivisiblemanager@3.4.0-canary.237.7ab2e27.0
npm install @quenty/hintscoringutils@4.5.0-canary.237.7ab2e27.0
npm install @quenty/idleservice@1.7.0-canary.237.7ab2e27.0
npm install @quenty/ik@4.7.0-canary.237.7ab2e27.0
npm install @quenty/lipsum@3.5.0-canary.237.7ab2e27.0
npm install @quenty/ragdoll@4.7.0-canary.237.7ab2e27.0
npm install @quenty/rotatinglabel@3.5.0-canary.237.7ab2e27.0
npm …
```
=> feat: Misc changes and adjustments

src/signal/src/Shared/SignalUtils.lua
<details>
<br />
```bash
npm install @quenty/actionmanager@3.5.2-canary.239.4af6d2a.0
npm install @quenty/attributeutils@4.0.2-canary.239.4af6d2a.0
npm install @quenty/basicpane@3.2.2-canary.239.4af6d2a.0
npm install @quenty/binder@4.5.2-canary.239.4af6d2a.0
npm install @quenty/blend@2.0.2-canary.239.4af6d2a.0
npm install @quenty/boundlinkutils@4.5.2-canary.239.4af6d2a.0
npm install @quenty/brio@3.5.2-canary.239.4af6d2a.0
npm install @quenty/buttonhighlightmodel@3.3.2-canary.239.4af6d2a.0
npm install @quenty/camera@5.0.2-canary.239.4af6d2a.0
npm install @quenty/canceltoken@3.3.2-canary.239.4af6d2a.0
npm install @quenty/cmdrservice@3.6.2-canary.239.4af6d2a.0
npm …
```
=> docs: Add documentation on SignalUtils

src/ragdoll/src/Client/Classes/RagdollClient.lua, src/ragdoll/src/Client/Classes/RagdollHumanoidOnDeathClient.lua, src/ragdoll/src/Client/Classes/RagdollHumanoidOnFallClient.lua, src/ragdoll/src/Client/Classes/RagdollableClient.lua, src/ragdoll/src/Client/RagdollBindersClient.lua, src/ragdoll/src/Server/Classes/Ragdoll.lua, src/ragdoll/src/Server/Classes/RagdollHumanoidOnDeath.lua, src/ragdoll/src/Server/Classes/RagdollHumanoidOnFall.lua, src/ragdoll/src/Server/Classes/Ragdollable.lua, src/ragdoll/src/Server/Classes/UnragdollAutomatically.lua, src/ragdoll/src/Server/RagdollBindersServer.lua, src/ragdoll/src/Shared/Classes/BindableRagdollHumanoidOnFall.lua, src/ragdoll/src/Shared/Classes/RagdollHumanoidOnFallConstants.lua, src/ragdoll/src/Shared/RagdollConstants.lua, src/ragdoll/src/Shared/RagdollRigging.lua, src/ragdoll/src/Shared/RagdollUtils.lua, src/ragdoll/src/Shared/RagdollableConstants.lua
<details>
<br />
```bash
npm install @quenty/idleservice@2.1.2-canary.243.ff1e5ed.0
npm install @quenty/ik@5.1.2-canary.243.ff1e5ed.0
npm install @quenty/ragdoll@5.1.2-canary.243.ff1e5ed.0
yarn add @quenty/idleservice@2.1.2-canary.243.ff1e5ed.0
yarn add @quenty/ik@5.1.2-canary.243.ff1e5ed.0
yarn add @quenty/ragdoll@5.1.2-canary.243.ff1e5ed.0
```
</details>
=> docs: Add documentation for ragdoll system

src/attributeutils/src/Shared/AttributeValue.lua, src/binder/src/Shared/BinderProvider.lua, src/binder/src/Shared/BinderProvider.spec.lua, src/blend/src/Shared/Blend/Blend.lua, src/blend/src/Shared/Test/BlendChildren.story.lua, src/brio/package.json, src/brio/src/Shared/RxBrioUtils.lua, src/buttonhighlightmodel/package.json, src/cmdrservice/package.json, src/cooldown/package.json, src/cooldown/src/Client/CooldownBindersClient.lua, src/cooldown/src/Client/CooldownClient.lua, src/cooldown/src/Server/Cooldown.lua, src/cooldown/src/Server/CooldownBindersServer.lua, src/cooldown/src/Shared/CooldownBase.lua, src/cooldown/src/Shared/CooldownConstants.lua, src/cooldown/src/Shared/CooldownUtils.lua, src/cooldown/src/Shared/RxCooldownUtils.lua, src/loader/src/GroupInfoUtils.lua, src/loader/src/LoaderConstants.lua, src/loader/src/PackageInfoUtils.lua, src/permissionprovider/src/Server/PermissionProviderUtils.lua, src/rx/src/Shared/Rx.spec.lua, src/statestack/src/Shared/StateStack.lua, src/valueobject/src/Shared/ValueObject.lua, src/valueobject/src/Shared/ValueObjectUtils.lua
<details>
<br />
```bash
npm install @quenty/actionmanager@3.6.1-canary.244.f59530a.0
npm install @quenty/animationgroup@3.3.1-canary.244.f59530a.0
npm install @quenty/animationprovider@3.6.1-canary.244.f59530a.0
npm install @quenty/applytagtotaggedchildren@3.3.1-canary.244.f59530a.0
npm install @quenty/attributeutils@4.1.1-canary.244.f59530a.0
npm install @quenty/badgeutils@3.4.1-canary.244.f59530a.0
npm install @quenty/baseobject@3.3.1-canary.244.f59530a.0
npm install @quenty/basicpane@3.3.1-canary.244.f59530a.0
npm install @quenty/binder@4.6.1-canary.244.f59530a.0
npm install @quenty/blend@2.1.2-canary.244.f59530a.0
npm install …
```
=> feat: Add Observable API surfaces to many objects and document cooldown. 

src/idleservice/package.json, src/idleservice/src/Client/IdleServiceClient.lua, src/statestack/package.json, src/statestack/src/Shared/RxStateStackUtils.lua, src/statestack/src/Shared/StateStack.lua
<details>
<br />
```bash
npm install @quenty/brio@3.8.1-canary.248.8acbdeb.0
npm install @quenty/idleservice@2.3.1-canary.248.8acbdeb.0
npm install @quenty/scoredactionservice@4.9.1-canary.248.8acbdeb.0
npm install @quenty/statestack@3.5.1-canary.248.8acbdeb.0
yarn add @quenty/brio@3.8.1-canary.248.8acbdeb.0
yarn add @quenty/idleservice@2.3.1-canary.248.8acbdeb.0
yarn add @quenty/scoredactionservice@4.9.1-canary.248.8acbdeb.0
yarn add @quenty/statestack@3.5.1-canary.248.8acbdeb.0
```
</details>
=> feat: Make breaking changes to idle service and statestack. 

src/cancellabledelay/src/Shared/cancellableDelay.lua, src/elo/README.md, src/elo/default.project.json, src/elo/package.json, src/elo/src/Shared/EloUtils.lua, src/elo/src/Shared/EloUtils.spec.lua, src/elo/test/default.project.json, src/gameconfig/src/Client/Config/Config/GameConfigClient.lua, src/gameconfig/src/Client/GameConfigServiceClient.lua, src/gameconfig/src/Client/GameConfigTranslator.lua, src/gameconfig/src/Server/Config/Config/GameConfig.lua, src/genericscreenguiprovider/package.json, src/genericscreenguiprovider/src/Client/GenericScreenGuiProvider.lua, src/hide/src/Shared/HideUtils.lua, src/maid/src/Shared/Maid.lua, src/multipleclickutils/package.json, src/multipleclickutils/src/Client/MultipleClickUtils.lua, src/spawning/.npmrc, src/spawning/README.md, src/spawning/default.project.json, src/spawning/package.json, src/spawning/src/Client/SpawnServiceClient.lua, src/spawning/src/Server/SpawnBinderGroupsServer.lua, src/spawning/src/Server/SpawnCmdrService.lua, src/spawning/src/Server/SpawnService.lua, src/spawning/src/Shared/SpawnerUtils.lua, src/spawning/src/node_modules.project.json, src/templateprovider/src/Shared/ModuleProvider.lua, src/templateprovider/src/Shared/ModuleProviderFakeLoader.lua, src/terrainutils/src/Shared/TerrainUtils.lua
<details>
<br />
```bash
npm install @quenty/actionmanager@4.1.0-canary.252.9753dcc.0
npm install @quenty/animationgroup@4.1.0-canary.252.9753dcc.0
npm install @quenty/animationprovider@4.1.0-canary.252.9753dcc.0
npm install @quenty/applytagtotaggedchildren@4.1.0-canary.252.9753dcc.0
npm install @quenty/attributeutils@5.1.0-canary.252.9753dcc.0
npm install @quenty/badgeutils@4.1.0-canary.252.9753dcc.0
npm install @quenty/baseobject@4.1.0-canary.252.9753dcc.0
npm install @quenty/basicpane@4.1.0-canary.252.9753dcc.0
npm install @quenty/binder@5.1.0-canary.252.9753dcc.0
npm install @quenty/blend@3.1.0-canary.252.9753dcc.0
npm install …
```
=> feat: Add elo package and a variety of other changes

src/characterutils/src/Shared/RxCharacterUtils.lua, src/cmdrservice/src/Server/CmdrService.lua, src/softshutdown/README.md, src/softshutdown/src/Client/SoftShutdownServiceClient.lua
<details>
<br />
```bash
npm install @quenty/characterutils@5.0.1-canary.269.5b9ce8a.0
npm install @quenty/cmdrservice@5.1.1-canary.269.5b9ce8a.0
npm install @quenty/coreguienabler@5.0.1-canary.269.5b9ce8a.0
npm install @quenty/deathreport@1.1.1-canary.269.5b9ce8a.0
npm install @quenty/equippedtracker@5.1.1-canary.269.5b9ce8a.0
npm install @quenty/gameconfig@3.1.1-canary.269.5b9ce8a.0
npm install @quenty/gameproductservice@3.1.1-canary.269.5b9ce8a.0
npm install @quenty/humanoidspeed@3.1.1-canary.269.5b9ce8a.0
npm install @quenty/idleservice@5.1.1-canary.269.5b9ce8a.0
npm install @quenty/ik@7.1.1-canary.269.5b9ce8a.0
npm install …
```
=> fix: Make a variety of more fixes around docs and admin commands

src/friendutils/src/Client/RxFriendUtils.lua
Utilities for observing the player's friends on the client. Reacts to friendships made in-game, and the friendship status of friends joining the server.
=> feat: RxFriendUtils

src/friendutils/src/Client/RxFriendUtils.lua
=> docs: Fix docs

default.project.json, src/friendutils/src/Client/RxFriendUtils.lua
<details>
<br />
```bash
npm install @quenty/adorneevalue@2.3.1-canary.280.f45f91e.0
npm install @quenty/blend@4.3.1-canary.280.f45f91e.0
npm install @quenty/buttonhighlightmodel@5.3.1-canary.280.f45f91e.0
npm install @quenty/clienttranslator@6.3.1-canary.280.f45f91e.0
npm install @quenty/color3utils@3.3.1-canary.280.f45f91e.0
npm install @quenty/colorpalette@2.3.1-canary.280.f45f91e.0
npm install @quenty/colorpicker@2.3.1-canary.280.f45f91e.0
npm install @quenty/conditions@2.2.1-canary.280.f45f91e.0
npm install @quenty/friendutils@5.1.1-canary.280.f45f91e.0
npm install @quenty/gameconfig@3.4.1-canary.280.f45f91e.0
npm install …
```
=> fix: Add metapackage default.project.json

src/signal/src/Shared/Signal.lua
Kept the code simple and just duplicated the `:Connect()` method. Should probably also add `:ConnectParallel()` too!
Closes #263
=> feat: Signal :Once(fn) method

src/playerutils/package.json, src/playerutils/src/Shared/RxPlayerUtils.lua, src/playerutils/src/node_modules.project.json
Adds RxPlayerUtils lib to PlayerUtils package
=> feat: Created RxPlayerUtils

.gitignore, .npmrc, selene.toml, src/blend/src/Shared/Blend/Blend.lua, src/camera/src/Client/CameraStack.lua, src/camera/src/Client/CameraStackService.lua, src/cmdrservice/.npmrc, src/cmdrservice/package.json, src/r15utils/src/Shared/RxR15Utils.lua, src/rodux-actions/.npmrc, src/rodux-actions/package.json, src/rogue-properties/.npmrc, src/rogue-properties/package.json, src/rxbinderutils/src/Shared/RxBinderUtils.lua, src/spawning/.npmrc, src/spawning/package.json, src/teamutils/src/Shared/RxTeamUtils.lua, src/tie/src/Shared/Definition/TieDefinition.lua, src/tie/src/Shared/Interface/TiePropertyInterface.lua, src/tie/src/Shared/Interface/TieSignalConnection.lua, src/viewport/src/Client/Viewport.lua
<details>
<br />
```bash
npm install @quenty/adorneevalue@4.2.0-canary.297.7020502.0
npm install @quenty/blend@6.2.0-canary.297.7020502.0
npm install @quenty/buttonhighlightmodel@7.2.0-canary.297.7020502.0
npm install @quenty/camera@9.2.0-canary.297.7020502.0
npm install @quenty/clienttranslator@8.2.0-canary.297.7020502.0
npm install @quenty/cmdrservice@7.2.0-canary.297.7020502.0
npm install @quenty/color3utils@5.2.0-canary.297.7020502.0
npm install @quenty/colorpalette@4.2.0-canary.297.7020502.0
npm install @quenty/colorpicker@4.2.0-canary.297.7020502.0
npm install @quenty/conditions@4.2.0-canary.297.7020502.0
npm install @quenty/cooldown@5.2.0-canary.297.7020502.0 …
```
=> fix: Can install via just NPM registry for now

src/ragdoll/src/Shared/RagdollConstants.lua, src/ragdoll/src/Shared/Rigging/RagdollBallSocketUtils.lua
<details>
<br />
```bash
npm install @quenty/idleservice@7.4.0-canary.300.bb72960.0
npm install @quenty/ik@9.4.0-canary.300.bb72960.0
npm install @quenty/ragdoll@9.4.0-canary.300.bb72960.0
yarn add @quenty/idleservice@7.4.0-canary.300.bb72960.0
yarn add @quenty/ik@9.4.0-canary.300.bb72960.0
yarn add @quenty/ragdoll@9.4.0-canary.300.bb72960.0
```
</details>
=> feat: Add Ragdoll customization

src/avatareditorutils/README.md, src/avatareditorutils/default.project.json, src/avatareditorutils/package.json, src/avatareditorutils/src/Client/AvatarEditorUtils.lua, src/avatareditorutils/src/node_modules.project.json, src/blend/src/Shared/Blend/SpringObject.lua, src/highlight/src/Client/AnimatedHighlight.lua, src/highlight/src/Client/AnimatedHighlightGroup.lua, src/ik/.gitignore, src/ik/package.json, src/ik/src/Shared/Arm/ArmIKBase.lua, src/playerutils/src/Shared/PlayerUtils.lua
<details>
<br />
```bash
npm install @quenty/adorneevalue@4.3.0-canary.301.3c6ceee.0
npm install @quenty/avatareditorutils@1.1.0-canary.301.3c6ceee.0
npm install @quenty/blend@6.3.0-canary.301.3c6ceee.0
npm install @quenty/buttonhighlightmodel@7.3.0-canary.301.3c6ceee.0
npm install @quenty/clienttranslator@8.3.0-canary.301.3c6ceee.0
npm install @quenty/color3utils@5.3.0-canary.301.3c6ceee.0
npm install @quenty/colorpalette@4.3.0-canary.301.3c6ceee.0
npm install @quenty/colorpicker@4.3.0-canary.301.3c6ceee.0
npm install @quenty/gameconfig@5.4.0-canary.301.3c6ceee.0
npm install @quenty/gameproductservice@5.4.0-canary.301.3c6ceee.0
npm install …
```
=> fix: A variety of fixes

src/colorpalette/README.md, src/colorpicker/README.md, src/colorpicker/src/Client/Cursor/HSColorPickerCursor.lua, src/colorpicker/src/Client/HSV/HSColorPicker.lua, src/colorpicker/src/Client/HSV/HSVColorPicker.lua, src/colorpicker/src/Client/HSV/ValueColorPicker.lua, src/softshutdown/src/Server/SoftShutdownService.lua, src/viewport/src/Client/Viewport.lua, src/viewport/src/Client/Viewport.story.lua, src/viewport/src/Client/ViewportControls.lua
I've been using some of the packages but found that they're undocumented, so I've documented some of them.
I've documented some of the softshutdown, colorpicker and viewport's packages. And also fixed the install method of colorpalette.
This is my first time contributing to the docs, so it'll not be perfect.
=> docs: Document a variety of packages

src/color3utils/src/Shared/luv/LuvUtils.lua, src/rx/src/Shared/Rx.lua
<details>
<br />
```bash
npm install @quenty/actionmanager@7.2.0-canary.311.4b33fd1.0
npm install @quenty/adorneevalue@4.5.0-canary.311.4b33fd1.0
npm install @quenty/attributeutils@8.2.0-canary.311.4b33fd1.0
npm install @quenty/avatareditorutils@1.3.0-canary.311.4b33fd1.0
npm install @quenty/basicpane@7.2.0-canary.311.4b33fd1.0
npm install @quenty/binder@8.4.0-canary.311.4b33fd1.0
npm install @quenty/blend@6.5.0-canary.311.4b33fd1.0
npm install @quenty/boundlinkutils@8.4.0-canary.311.4b33fd1.0
npm install @quenty/brio@8.2.0-canary.311.4b33fd1.0
npm install @quenty/buttonhighlightmodel@7.5.0-canary.311.4b33fd1.0
npm install …
```
=> feat: Add Rx.failed()

src/buttonhighlightmodel/src/Client/HandleHighlightModel.lua, src/camera/src/Client/Controls/CameraControls.lua, src/camera/src/Client/Controls/GamepadRotateModel.lua, src/cframeutils/src/Shared/CFrameUtils.lua, src/clienttranslator/src/Client/JSONTranslator.lua, src/geometryutils/package.json, src/geometryutils/src/Shared/CameraPyramidUtils.lua, src/geometryutils/src/node_modules.project.json, src/hintscoringutils/src/Client/HintScoringUtils.lua, src/ragdoll/package.json, src/rigbuilderutils/test/default.project.json, src/servicebag/src/Shared/ServiceBag.lua, src/vector3utils/src/Shared/Vector3SerializationUtils.lua, src/vector3utils/src/Shared/Vector3Utils.lua
<details>
<br />
```bash
npm install @quenty/buttonhighlightmodel@7.4.1-canary.312.d20c26e.0
npm install @quenty/camera@9.5.1-canary.312.d20c26e.0
npm install @quenty/cframeutils@5.0.1-canary.312.d20c26e.0
npm install @quenty/clienttranslator@8.5.1-canary.312.d20c26e.0
npm install @quenty/cmdrservice@7.5.1-canary.312.d20c26e.0
npm install @quenty/cooldown@5.5.2-canary.312.d20c26e.0
npm install @quenty/deathreport@3.5.1-canary.312.d20c26e.0
npm install @quenty/gameconfig@5.6.2-canary.312.d20c26e.0
npm install @quenty/gameproductservice@5.6.2-canary.312.d20c26e.0
npm install @quenty/geometryutils@2.2.1-canary.312.d20c26e.0
npm install …
```
=> feat: Minor adjustments

src/rx/src/Shared/Observable.lua
=> docs: Update Observable.lua

src/coreguienabler/package.json, src/coreguienabler/src/Client/CoreGuiEnabler.lua, src/playerutils/src/Shared/RxPlayerUtils.lua, src/rx/src/Shared/Rx.lua, src/softshutdown/package.json, src/softshutdown/src/Client/SoftShutdownServiceClient.lua
<details>
<br />
```bash
npm install @quenty/actionmanager@7.4.0-canary.320.2958baa.0
npm install @quenty/adorneevalue@4.7.0-canary.320.2958baa.0
npm install @quenty/attributeutils@8.4.0-canary.320.2958baa.0
npm install @quenty/avatareditorutils@1.5.0-canary.320.2958baa.0
npm install @quenty/basicpane@7.4.0-canary.320.2958baa.0
npm install @quenty/binder@8.6.0-canary.320.2958baa.0
npm install @quenty/blend@6.7.0-canary.320.2958baa.0
npm install @quenty/boundlinkutils@8.6.0-canary.320.2958baa.0
npm install @quenty/brio@8.4.0-canary.320.2958baa.0
npm install @quenty/buttonhighlightmodel@7.8.0-canary.320.2958baa.0
npm install …
```
=> fix: CoreGuiEnabler disables and observes nicely

src/cancellabledelay/README.md, src/experiencecalculator/README.md, src/firstpersoncharactertransparency/README.md, src/inputmode/README.md, src/loader/README.md, src/motor6d/README.md, src/qgui/README.md, src/rodux-actions/README.md, src/rodux-undo/README.md, src/selectionutils/README.md, src/string/README.md, src/symbol/README.md, src/table/README.md, src/tie/README.md, src/uiobjectutils/README.md, src/undostack/README.md, src/viewport/README.md
=> docs: fixing broken links

src/avatareditorutils/src/Shared/AvatarEditorUtils.lua, src/brio/src/Shared/RxBrioUtils.lua, src/gameconfig/src/Server/Cmdr/GameConfigCommandService.lua, src/gameconfig/src/Server/GameConfigService.lua, src/gameconfig/src/Shared/Config/Asset/GameConfigAssetBase.lua, src/gameconfig/src/Shared/Config/AssetTypes/GameConfigAssetTypeUtils.lua, src/gameconfig/src/Shared/Config/AssetTypes/GameConfigAssetTypes.lua, src/gameconfig/src/Shared/Config/Picker/GameConfigPicker.lua, src/marketplaceutils/src/Shared/MarketplaceUtils.lua, src/promise/src/Shared/Utility/PendingPromiseTracker.lua, src/promise/src/Shared/Utility/PromiseInstanceUtils.lua, src/promise/src/Shared/Utility/promisePropertyValue.lua, src/promise/src/Shared/Utility/promiseWait.lua, src/pseudolocalize/src/Shared/PseudoLocalize.lua, src/statestack/src/Shared/RxStateStackUtils.lua
<details>
<br />
```bash
npm install @quenty/actionmanager@7.5.1-canary.330.de4a2f4.0
npm install @quenty/adorneevalue@4.8.1-canary.330.de4a2f4.0
npm install @quenty/animationprovider@7.1.1-canary.330.de4a2f4.0
npm install @quenty/attributeutils@8.6.1-canary.330.de4a2f4.0
npm install @quenty/avatareditorutils@1.6.1-canary.330.de4a2f4.0
npm install @quenty/badgeutils@6.1.1-canary.330.de4a2f4.0
npm install @quenty/basicpane@7.5.1-canary.330.de4a2f4.0
npm install @quenty/binder@8.7.1-canary.330.de4a2f4.0
npm install @quenty/bindtocloseservice@2.2.1-canary.330.de4a2f4.0
npm install @quenty/blend@6.8.1-canary.330.de4a2f4.0
npm install …
```
=> feat: Add small documentation and other changes to libraries

src/rbxthumb/package.json, src/rbxthumb/src/Shared/RbxThumbUtils.lua, src/rbxthumb/src/Shared/RbxThumbnailTypes.lua
<details>
<br />
```bash
npm install @quenty/rbxthumb@1.2.0-canary.332.496f505.0
yarn add @quenty/rbxthumb@1.2.0-canary.332.496f505.0
```
</details>
=> feat: Add RbxThumbUtils.avatarItemTypeToThumbnailType(avatarItemType)

src/enumutils/src/Shared/EnumUtils.lua, src/gameproductservice/src/Client/GameProductServiceClient.lua, src/gameproductservice/src/Server/GameProductService.lua, src/gameproductservice/src/Shared/Helpers/GameProductServiceHelper.lua
<details>
<br />
```bash
npm install @quenty/avatareditorutils@1.8.0-canary.334.4712dec.0
npm install @quenty/enumutils@3.1.0-canary.334.4712dec.0
npm install @quenty/gameproductservice@6.1.0-canary.334.4712dec.0
npm install @quenty/highlight@2.12.0-canary.334.4712dec.0
npm install @quenty/idleservice@7.14.0-canary.334.4712dec.0
npm install @quenty/ik@9.15.0-canary.334.4712dec.0
npm install @quenty/inputkeymaputils@7.15.0-canary.334.4712dec.0
npm install @quenty/ragdoll@9.14.0-canary.334.4712dec.0
npm install @quenty/scoredactionservice@9.15.0-canary.334.4712dec.0
npm install @quenty/settings-inputkeymap@3.17.0-canary.334.4712dec.0
npm install …
```
=> feat: Add EnumUtils.toEnum(enumType, value)

.gitignore, docs/servicebag.md, tools/nevermore-cli/templates/game-template/gitignore, tools/nevermore-template-helpers/package-lock.json, tools/nevermore-template-helpers/src/templateHelpers.ts
<details>
<br />
```bash
npm install @quenty/nevermore-cli@1.5.1-canary.336.24deebc.0
npm install @quenty/nevermore-template-helpers@1.2.1-canary.336.24deebc.0
yarn add @quenty/nevermore-cli@1.5.1-canary.336.24deebc.0
yarn add @quenty/nevermore-template-helpers@1.2.1-canary.336.24deebc.0
```
</details>
=> docs: Add ServiceBag docs

src/clienttranslator/src/Client/JSONTranslator.lua, src/pseudolocalize/src/Shared/PseudoLocalize.lua, src/tie/package.json
<details>
<br />
```bash
npm install @quenty/clienttranslator@8.14.0-canary.343.3790994.0
npm install @quenty/conditions@4.11.0-canary.343.3790994.0
npm install @quenty/gameconfig@5.18.0-canary.343.3790994.0
npm install @quenty/gameproductservice@6.4.0-canary.343.3790994.0
npm install @quenty/idleservice@7.16.0-canary.343.3790994.0
npm install @quenty/ik@9.17.0-canary.343.3790994.0
npm install @quenty/inputkeymaputils@7.18.0-canary.343.3790994.0
npm install @quenty/motor6d@1.14.0-canary.343.3790994.0
npm install @quenty/pseudolocalize@3.2.0-canary.343.3790994.0
npm install @quenty/ragdoll@9.16.0-canary.343.3790994.0
npm install …
```
=> Localization changes

src/buttonhighlightmodel/package.json, src/buttonhighlightmodel/src/Client/ButtonHighlightModel.lua
<details>
<br />
```bash
npm install @quenty/buttonhighlightmodel@8.0.0-canary.346.8006865.0
yarn add @quenty/buttonhighlightmodel@8.0.0-canary.346.8006865.0
```
</details>
=> feat!: Refactor ButtonHighlightModel API contract

src/gameproductservice/src/Server/GameProductService.lua
<details>
<br />
```bash
npm install @quenty/gameproductservice@7.0.0-canary.350.0df5062.0
yarn add @quenty/gameproductservice@7.0.0-canary.350.0df5062.0
```
</details>
=> feat!: Add game product service :BindProcessReceipt() call

src/loader/src/PackageInfoUtils.lua
<details>
<br />
```bash
npm install @quenty/actionmanager@7.11.1-canary.351.777f5eb.0
npm install @quenty/adorneevalue@4.15.1-canary.351.777f5eb.0
npm install @quenty/animationgroup@6.2.1-canary.351.777f5eb.0
npm install @quenty/animationprovider@7.5.1-canary.351.777f5eb.0
npm install @quenty/applytagtotaggedchildren@6.2.1-canary.351.777f5eb.0
npm install @quenty/assetserviceutils@1.2.1-canary.351.777f5eb.0
npm install @quenty/attributeutils@8.11.1-canary.351.777f5eb.0
npm install @quenty/avatareditorutils@1.12.1-canary.351.777f5eb.0
npm install @quenty/badgeutils@6.4.1-canary.351.777f5eb.0
npm install @quenty/baseobject@6.2.1-canary.351.777f5eb.0
npm install …
```
=> fix: Loader provides better error message

src/colorpalette/src/Shared/Font/FontPalette.lua
<details>
<br />
```bash
npm install @quenty/actionmanager@7.12.0-canary.352.3411e11.0
npm install @quenty/adorneevalue@4.16.0-canary.352.3411e11.0
npm install @quenty/animationgroup@6.3.0-canary.352.3411e11.0
npm install @quenty/animationprovider@7.6.0-canary.352.3411e11.0
npm install @quenty/applytagtotaggedchildren@6.3.0-canary.352.3411e11.0
npm install @quenty/assetserviceutils@1.3.0-canary.352.3411e11.0
npm install @quenty/attributeutils@8.12.0-canary.352.3411e11.0
npm install @quenty/avatareditorutils@1.13.0-canary.352.3411e11.0
npm install @quenty/badgeutils@6.5.0-canary.352.3411e11.0
npm install @quenty/baseobject@6.3.0-canary.352.3411e11.0
npm install …
```
=> feat: Add FontPalette:GetFontFaceValue(fontName)

src/gameproductservice/package.json, src/gameproductservice/src/Shared/Ownership/PlayerAssetOwnershipTracker.lua
<details>
<br />
```bash
npm install @quenty/gameproductservice@7.0.2-canary.353.4f44f2f.0
yarn add @quenty/gameproductservice@7.0.2-canary.353.4f44f2f.0
```
</details>
=> fix: Fix dependencies and ownership promise

src/camerainfo/README.md, src/camerainfo/default.project.json, src/camerainfo/package.json, src/camerainfo/src/Shared/CameraInfoUtils.lua, src/collectionserviceutils/package.json, src/flipbook/package.json, src/friendutils/package.json, src/gameproductservice/package.json, src/inputmode/src/Shared/InputModeType.lua, src/permissionprovider/src/Client/PermissionServiceClient.lua, src/permissionprovider/src/Client/Providers/PermissionProviderClient.lua, src/permissionprovider/src/Server/PermissionService.lua, src/playerutils/package.json, src/seatutils/package.json, src/seatutils/src/Shared/RxSeatUtils.lua, src/secrets/package.json, src/uiobjectutils/src/Client/UIAlignmentUtils.lua
<details>
<br />
```bash
npm install @quenty/camerainfo@1.0.1-canary.359.c006846.0
npm install @quenty/cmdrservice@7.13.1-canary.359.c006846.0
npm install @quenty/collectionserviceutils@2.12.1-canary.359.c006846.0
npm install @quenty/flipbook@2.5.1-canary.359.c006846.0
npm install @quenty/friendutils@6.6.1-canary.359.c006846.0
npm install @quenty/gameconfig@5.24.1-canary.359.c006846.0
npm install @quenty/gameproductservice@7.2.1-canary.359.c006846.0
npm install @quenty/genericscreenguiprovider@7.17.1-canary.359.c006846.0
npm install @quenty/inputkeymaputils@7.24.1-canary.359.c006846.0
npm install @quenty/inputmode@7.16.1-canary.359.c006846.0
npm install …
```
=> fix: Do additional fixes

src/gameproductservice/src/Server/GameProductService.lua, src/gameproductservice/src/Shared/Trackers/PlayerAssetMarketTracker.lua
<details>
<br />
```bash
npm install @quenty/camerainfo@1.0.1-canary.360.e789a63.0
npm install @quenty/cmdrservice@7.13.1-canary.360.e789a63.0
npm install @quenty/collectionserviceutils@2.12.1-canary.360.e789a63.0
npm install @quenty/flipbook@2.5.1-canary.360.e789a63.0
npm install @quenty/friendutils@6.6.1-canary.360.e789a63.0
npm install @quenty/gameconfig@5.24.1-canary.360.e789a63.0
npm install @quenty/gameproductservice@7.2.1-canary.360.e789a63.0
npm install @quenty/genericscreenguiprovider@7.17.1-canary.360.e789a63.0
npm install @quenty/inputkeymaputils@7.24.1-canary.360.e789a63.0
npm install @quenty/inputmode@7.16.1-canary.360.e789a63.0
npm install …
```
=> fix: Ensure processing is handled properly

aftman.toml, games/integration/aftman.toml, src/binder/package.json, src/binder/src/Shared/Binder.lua, src/binder/src/Shared/BinderProvider.lua, src/collectionserviceutils/src/Shared/CollectionServiceUtils.lua, src/playerhumanoidbinder/src/Server/PlayerCharacterBinder.lua, src/playerhumanoidbinder/src/Server/PlayerHumanoidBinder.lua, src/promise/src/Shared/PromiseUtils.lua, src/ragdoll/src/Shared/Rigging/RxRagdollUtils.lua, src/remotefunctionutils/src/Shared/RemoteFunctionUtils.lua, src/remoting/package.json, src/remoting/src/Shared/Interface/Remoting.lua, src/remoting/src/Shared/Interface/RemotingMember.lua, src/undostack/package.json, src/undostack/src/Shared/UndoStack.lua, src/undostack/src/Shared/UndoStackEntry.lua, tools/nevermore-cli/templates/game-template/aftman.toml
<details>
<br />
```bash
npm install @quenty/actionmanager@7.15.1-canary.367.3b0218a.0
npm install @quenty/adorneevalue@4.19.1-canary.367.3b0218a.0
npm install @quenty/animationprovider@7.6.1-canary.367.3b0218a.0
npm install @quenty/assetserviceutils@1.3.1-canary.367.3b0218a.0
npm install @quenty/attributeutils@8.15.1-canary.367.3b0218a.0
npm install @quenty/avatareditorutils@1.15.1-canary.367.3b0218a.0
npm install @quenty/badgeutils@6.5.1-canary.367.3b0218a.0
npm install @quenty/basicpane@7.14.1-canary.367.3b0218a.0
npm install @quenty/binder@8.17.1-canary.367.3b0218a.0
npm install @quenty/bindtocloseservice@2.12.1-canary.367.3b0218a.0
npm install …
```
=> Update binders, add remoting contract, and more

src/highlight/package.json, src/highlight/src/Client/AnimatedHighlight.lua, src/highlight/src/Client/AnimatedHighlightGroup.lua, src/highlight/src/Client/AnimatedHighlightGroup.story.lua, src/highlight/src/Client/HighlightServiceClient.lua, src/highlight/src/Client/Stack/AnimatedHighlightModel.lua, src/highlight/src/Client/Stack/AnimatedHighlightStack.lua
<details>
<br />
```bash
npm install @quenty/highlight@3.0.0-canary.371.a75d8ee.0
yarn add @quenty/highlight@3.0.0-canary.371.a75d8ee.0
```
</details>
=> feat!: Breaking change on highlights to make it OOP

src/ragdoll/src/Shared/Rigging/RxRagdollUtils.lua
https://github.com/Quenty/NevermoreEngine/assets/1774409/2610e0a2-987a-44d9-8da7-f8a7ef929bfb
=> fix: Fix death respawn noise spam

src/blend/src/Shared/Blend/Blend.lua
<details>
<br />
```bash
npm install @quenty/adorneevalue@4.21.1-canary.388.ec32475.0
npm install @quenty/blend@6.21.1-canary.388.ec32475.0
npm install @quenty/bodycolorsutils@1.11.1-canary.388.ec32475.0
npm install @quenty/buttonhighlightmodel@8.9.1-canary.388.ec32475.0
npm install @quenty/clienttranslator@8.24.1-canary.388.ec32475.0
npm install @quenty/color3utils@5.22.1-canary.388.ec32475.0
npm install @quenty/colorpalette@4.26.1-canary.388.ec32475.0
npm install @quenty/colorpicker@4.23.1-canary.388.ec32475.0
npm install @quenty/gameconfig@5.31.1-canary.388.ec32475.0
npm install @quenty/gameproductservice@7.9.1-canary.388.ec32475.0
npm install …
```
=> docs: Update blend docs

src/attributeutils/src/Shared/AttributeValue.lua, src/binder/src/Shared/Binder.lua, src/blend/src/Shared/Blend/Blend.lua, src/blend/src/Shared/Blend/SpringObject.lua, src/cframeutils/src/Shared/CFrameUtils.lua, src/humanoidteleportutils/src/Shared/HumanoidTeleportUtils.lua, src/observablecollection/src/Shared/ObservableSet.lua, src/propertyvalue/README.md, src/propertyvalue/default.project.json, src/propertyvalue/package.json, src/propertyvalue/src/Shared/PropertyValue.lua, src/propertyvalue/src/node_modules.project.json, src/rogue-properties/src/Shared/Modifiers/Additive/RogueAdditiveProvider.lua, src/rogue-properties/src/Shared/Modifiers/Multiplier/RogueMultiplierProvider.lua, src/rogue-properties/src/Shared/Modifiers/Setter/RogueSetterProvider.lua, src/rogue-properties/src/Shared/Property/RogueProperty.lua, src/rx/src/Shared/Rx.lua, src/rxsignal/README.md, src/rxsignal/default.project.json, src/rxsignal/package.json, src/rxsignal/src/Shared/RxSignal.lua, src/rxsignal/src/node_modules.project.json, src/tie/src/Shared/Definition/TieDefinition.lua, src/tie/src/Shared/Interface/TiePropertyInterface.lua, src/valuebaseutils/package.json, src/valuebaseutils/src/Shared/ValueBaseValue.lua
<details>
<br />
```bash
npm install @quenty/actionmanager@7.18.0-canary.393.f2914a6.0
npm install @quenty/adorneeboundingbox@1.3.0-canary.393.f2914a6.0
npm install @quenty/adorneevalue@4.22.0-canary.393.f2914a6.0
npm install @quenty/attributeutils@8.17.0-canary.393.f2914a6.0
npm install @quenty/avatareditorutils@1.17.0-canary.393.f2914a6.0
npm install @quenty/basicpane@7.16.0-canary.393.f2914a6.0
npm install @quenty/binder@8.21.0-canary.393.f2914a6.0
npm install @quenty/bindtocloseservice@2.15.0-canary.393.f2914a6.0
npm install @quenty/blend@6.22.0-canary.393.f2914a6.0
npm install @quenty/bodycolorsutils@1.12.0-canary.393.f2914a6.0
npm install …
```
=> Add :Observe() API calls to a variety of places

src/camera/package.json, src/camera/src/Client/CameraStack.lua, src/camera/src/Client/Effects/ImpulseCamera.lua, src/camera/src/Client/Effects/ImpulseCamera.story.lua
<details>
<br />
```bash
npm install @quenty/camera@9.19.0-canary.399.31a7a55.0
npm install @quenty/hintscoringutils@9.21.0-canary.399.31a7a55.0
npm install @quenty/idleservice@7.32.0-canary.399.31a7a55.0
npm install @quenty/ik@9.34.0-canary.399.31a7a55.0
npm install @quenty/ragdoll@9.32.0-canary.399.31a7a55.0
npm install @quenty/viewport@5.31.0-canary.399.31a7a55.0
yarn add @quenty/camera@9.19.0-canary.399.31a7a55.0
yarn add @quenty/hintscoringutils@9.21.0-canary.399.31a7a55.0
yarn add @quenty/idleservice@7.32.0-canary.399.31a7a55.0
yarn add @quenty/ik@9.34.0-canary.399.31a7a55.0
yarn add @quenty/ragdoll@9.32.0-canary.399.31a7a55.0
yarn add …
```
=> feat: Allow for layered camera impulse

src/datastore/src/Server/DataStore.lua
=> Fix DataStore.lua documentation type

src/datastore/src/Server/Modules/DataStoreStage.lua
<details>
<br />
```bash
npm install @quenty/datastore@7.25.2-canary.410.f9032d0.0
npm install @quenty/secrets@1.18.2-canary.410.f9032d0.0
npm install @quenty/settings-inputkeymap@3.41.2-canary.410.f9032d0.0
npm install @quenty/settings@4.37.2-canary.410.f9032d0.0
npm install @quenty/softshutdown@3.40.2-canary.410.f9032d0.0
yarn add @quenty/datastore@7.25.2-canary.410.f9032d0.0
yarn add @quenty/secrets@1.18.2-canary.410.f9032d0.0
yarn add @quenty/settings-inputkeymap@3.41.2-canary.410.f9032d0.0
yarn add @quenty/settings@4.37.2-canary.410.f9032d0.0
yarn add @quenty/softshutdown@3.40.2-canary.410.f9032d0.0
```
</details>
=> fix: Ensure default value is returned in certain nil scenarios

src/observablecollection/src/Shared/ObservableMapSet.lua, src/observablecollection/src/Shared/ObservableSet.lua
<details>
<br />
```bash
npm install @quenty/adorneeboundingbox@2.1.0-canary.419.a1141f4.0
npm install @quenty/flipbook@3.1.0-canary.419.a1141f4.0
npm install @quenty/gameconfig@6.1.0-canary.419.a1141f4.0
npm install @quenty/gameproductservice@8.1.0-canary.419.a1141f4.0
npm install @quenty/highlight@4.1.0-canary.419.a1141f4.0
npm install @quenty/inputkeymaputils@8.1.0-canary.419.a1141f4.0
npm install @quenty/inputmode@8.1.0-canary.419.a1141f4.0
npm install @quenty/observablecollection@6.1.0-canary.419.a1141f4.0
npm install @quenty/playerinputmode@4.1.0-canary.419.a1141f4.0
npm install @quenty/scoredactionservice@10.1.0-canary.419.a1141f4.0
npm install …
```
=> feat: Add ObservableMapSet:GetKeyList()

src/elo/package.json, src/elo/src/Shared/EloMatchResult.lua, src/elo/src/Shared/EloMatchResultUtils.lua, src/elo/src/Shared/EloUtils.lua, src/elo/src/Shared/EloUtils.spec.lua, src/elo/src/Shared/EloUtils.story.lua
<details>
<br />
```bash
npm install @quenty/elo@2.0.0-canary.424.2e1c7a7.0
yarn add @quenty/elo@2.0.0-canary.424.2e1c7a7.0
```
</details>
=> feat!: Refactor EloUtils to be easier to use and visualize elo utils

src/observablecollection/src/Shared/ObservableMapList.lua
This was bugging me for a while.
=> fix: Fix function implementations/names in ObservableList

src/playerutils/src/Shared/RxPlayerUtils.lua
<details>
<br />
```bash
npm install @quenty/chatproviderservice@4.1.0-canary.421.981663f.0
npm install @quenty/cmdrservice@8.1.0-canary.421.981663f.0
npm install @quenty/gameconfig@6.2.0-canary.421.981663f.0
npm install @quenty/gameproductservice@8.2.0-canary.421.981663f.0
npm install @quenty/permissionprovider@9.1.0-canary.421.981663f.0
npm install @quenty/playerutils@3.1.0-canary.421.981663f.0
npm install @quenty/secrets@2.1.0-canary.421.981663f.0
npm install @quenty/settings-inputkeymap@4.3.0-canary.421.981663f.0
npm install @quenty/settings@5.2.0-canary.421.981663f.0
npm install @quenty/spawning@5.1.0-canary.421.981663f.0
yarn add …
```
=> fix: no yield so task spawn in for loop

src/rxbinderutils/src/Shared/RxBinderUtils.lua
Fast way to observe all classes bound to a binder as an array. I doubt a non-brio version (`RxBinderUtils.observeAllArray`) would be that useful.
=> feat: RxBinderUtils.observeAllArrayBrio

lerna.json, package.json, src/countdowntext/package.json, src/loader/package.json, src/queue/package.json
<details>
<br />
```bash
npm install @quenty/actionmanager@8.3.1-canary.438.a2f46f8.0
npm install @quenty/adorneeboundingbox@2.4.1-canary.438.a2f46f8.0
npm install @quenty/adorneedata@1.2.1-canary.438.a2f46f8.0
npm install @quenty/adorneevalue@5.3.1-canary.438.a2f46f8.0
npm install @quenty/animationgroup@7.1.1-canary.438.a2f46f8.0
npm install @quenty/animationprovider@8.1.1-canary.438.a2f46f8.0
npm install @quenty/animations@2.3.1-canary.438.a2f46f8.0
npm install @quenty/applytagtotaggedchildren@7.1.1-canary.438.a2f46f8.0
npm install @quenty/assetserviceutils@2.1.1-canary.438.a2f46f8.0
npm install @quenty/attributeutils@9.3.1-canary.438.a2f46f8.0
npm install …
```
=> ci: Upgrade to latest auto-it and lerna

plugins/ui-converter-plugin/src/modules/Server/ConverterPane.lua, src/marketplaceutils/src/Shared/MarketplaceUtils.lua, src/observablecollection/src/Shared/FilteredObservableListView.lua, src/observablecollection/src/Shared/ObservableSortedList.lua, src/sprites/src/Shared/InputImageLibrary/init.lua
<details>
<br />
```bash
npm install @quenty/actionmanager@11.0.1-canary.445.bf8e4c3.0
npm install @quenty/adorneeboundingbox@5.0.1-canary.445.bf8e4c3.0
npm install @quenty/adorneedata@5.0.1-canary.445.bf8e4c3.0
npm install @quenty/adorneevalue@8.0.1-canary.445.bf8e4c3.0
npm install @quenty/animationgroup@8.0.1-canary.445.bf8e4c3.0
npm install @quenty/animationprovider@9.0.1-canary.445.bf8e4c3.0
npm install @quenty/animations@5.0.1-canary.445.bf8e4c3.0
npm install @quenty/applytagtotaggedchildren@8.0.1-canary.445.bf8e4c3.0
npm install @quenty/assetserviceutils@3.0.1-canary.445.bf8e4c3.0
npm install @quenty/attributeutils@12.0.1-canary.445.bf8e4c3.0
npm install …
```
=> fix: Remove info type as nil

src/loader/src2/Dependencies/PackageTracker.lua, src/loader/src2/Dependencies/PackageTrackerProvider.lua
<details>
<br />
```bash
npm install @quenty/actionmanager@12.0.1-canary.446.cd67bf3.0
npm install @quenty/adorneeboundingbox@7.0.1-canary.446.cd67bf3.0
npm install @quenty/adorneedata@6.0.1-canary.446.cd67bf3.0
npm install @quenty/adorneevalue@9.0.1-canary.446.cd67bf3.0
npm install @quenty/animationgroup@9.0.1-canary.446.cd67bf3.0
npm install @quenty/animationprovider@10.0.1-canary.446.cd67bf3.0
npm install @quenty/animations@6.0.1-canary.446.cd67bf3.0
npm install @quenty/applytagtotaggedchildren@9.0.1-canary.446.cd67bf3.0
npm install @quenty/assetserviceutils@4.0.1-canary.446.cd67bf3.0
npm install @quenty/attributeutils@13.0.1-canary.446.cd67bf3.0
npm install …
```
=> fix: Fix loader tracking going infinite

src/octree/src/Shared/OctreeRegionUtils.lua
<details>
<br />
```bash
npm install @quenty/octree@10.1.0-canary.449.e177648.0
yarn add @quenty/octree@10.1.0-canary.449.e177648.0
```
</details>
=> perf: Use native compilation on OctreeRegionUtils

readme.md
=> docs: Update readme.md

aftman.toml, games/integration/aftman.toml, selene.toml, tools/nevermore-cli/templates/game-template/aftman.toml, tools/nevermore-cli/templates/game-template/selene.toml
<details>
<br />
```bash
npm install @quenty/nevermore-cli@4.0.1-canary.454.a99b017.0
yarn add @quenty/nevermore-cli@4.0.1-canary.454.a99b017.0
```
</details>
=> ci: Update to use selene 26.1

src/assetserviceutils/package.json, src/avatareditorutils/src/Shared/AvatarEditorUtils.lua, src/binder/src/Shared/BinderProvider.lua, src/cmdrservice/src/Client/CmdrServiceClient.lua, src/gameconfig/src/Client/Cmdr/GameConfigCommandServiceClient.lua, src/gameproductservice/src/Client/GameProductServiceClient.lua, src/genericscreenguiprovider/src/Client/GenericScreenGuiProvider.lua, src/genericscreenguiprovider/src/Client/ScreenGuiService.lua, src/inputobjectutils/package.json, src/inputobjectutils/src/Client/InputObjectPositionTracker.lua, src/permissionprovider/src/Client/PermissionServiceClient.lua, src/remoting/src/Shared/Interface/Remoting.lua, src/rogue-properties/src/Shared/Modifiers/Additive/RogueAdditiveProvider.lua, src/rogue-properties/src/Shared/Modifiers/Multiplier/RogueMultiplierProvider.lua, src/rogue-properties/src/Shared/Modifiers/Setter/RogueSetterProvider.lua, src/scoredactionservice/src/Client/ScoredActionServiceClient.lua, src/tie/src/Shared/Definition/TiePropertyDefinition.lua, src/timesyncservice/src/Shared/TimeSyncService.lua
<details>
<br />
```bash
npm install @quenty/assetserviceutils@5.1.1-canary.456.711b68e.0
npm install @quenty/avatareditorutils@7.1.1-canary.456.711b68e.0
npm install @quenty/binder@14.1.1-canary.456.711b68e.0
npm install @quenty/boundlinkutils@14.1.1-canary.456.711b68e.0
npm install @quenty/camera@14.1.1-canary.456.711b68e.0
npm install @quenty/chatproviderservice@9.2.1-canary.456.711b68e.0
npm install @quenty/clipcharacters@12.1.1-canary.456.711b68e.0
npm install @quenty/cmdrservice@13.1.1-canary.456.711b68e.0
npm install @quenty/colorpalette@10.1.1-canary.456.711b68e.0
npm install @quenty/colorpicker@10.1.1-canary.456.711b68e.0
npm install …
```
=> feat: Update avatar editor updates

tools/nevermore-cli/README.md, tools/nevermore-cli/src/commands/init-plugin-command.ts, tools/nevermore-cli/src/nevermore.ts, tools/nevermore-cli/templates/plugin-template/README.md, tools/nevermore-cli/templates/plugin-template/aftman.toml, tools/nevermore-cli/templates/plugin-template/default.project.json, tools/nevermore-cli/templates/plugin-template/gitignore, tools/nevermore-cli/templates/plugin-template/package.json, tools/nevermore-cli/templates/plugin-template/selene.toml, tools/nevermore-cli/templates/plugin-template/src/init.server.lua, tools/nevermore-cli/templates/plugin-template/{{pluginName}}.sublime-project
Creates a command that lets you quickly initialize a repo for a Nevermore plugin.
<details>
<br />
```bash
npm install @quenty/nevermore-cli@4.2.1-canary.489.68e24c9.0
yarn add @quenty/nevermore-cli@4.2.1-canary.489.68e24c9.0
```
</details>
=> feat: Add init-plugin command

src/ragdoll/src/Shared/Rigging/RxRagdollUtils.lua
<details>
<br />
```bash
npm install @quenty/idleservice@13.7.1-canary.491.adb5527.0
npm install @quenty/ik@15.8.1-canary.491.adb5527.0
npm install @quenty/ragdoll@15.7.1-canary.491.adb5527.0
yarn add @quenty/idleservice@13.7.1-canary.491.adb5527.0
yarn add @quenty/ik@15.8.1-canary.491.adb5527.0
yarn add @quenty/ragdoll@15.7.1-canary.491.adb5527.0
```
</details>
=> fix: Upgrade ragdoll to support humanoid state machine off

src/animations/src/Shared/AnimationSlotPlayer.lua, src/blend/src/Shared/Blend/SpringObject.lua, src/radial-image/src/Client/RadialImage.lua, src/rogue-properties/src/Shared/Modifiers/Implementations/RogueSetter.lua, src/spring/src/Shared/LinearValue.lua
<details>
<br />
```bash
npm install @quenty/adorneeboundingbox@8.5.2-canary.498.448f708.0
npm install @quenty/adorneevalue@10.5.2-canary.498.448f708.0
npm install @quenty/animations@8.5.1-canary.498.448f708.0
npm install @quenty/blend@12.5.2-canary.498.448f708.0
npm install @quenty/bodycolorsutils@7.5.2-canary.498.448f708.0
npm install @quenty/buttonhighlightmodel@14.5.2-canary.498.448f708.0
npm install @quenty/camera@14.7.2-canary.498.448f708.0
npm install @quenty/chatproviderservice@9.9.2-canary.498.448f708.0
npm install @quenty/clienttranslator@14.6.2-canary.498.448f708.0
npm install @quenty/color3utils@11.5.2-canary.498.448f708.0
npm install …
```
=> fix: Fix SpringObject and a few other bugs in the system

src/coreguienabler/src/Client/CoreGuiEnabler.lua, src/rx/src/Shared/Rx.lua, src/softshutdown/src/Client/SoftShutdownServiceClient.lua
fix: Rx.defaultsTo() would fire events during completion or fail, which it should not
<details>
<br />
```bash
npm install @quenty/actionmanager@13.5.1-canary.499.60b3012.0
npm install @quenty/adorneeboundingbox@8.5.3-canary.499.60b3012.0
npm install @quenty/adorneedata@7.6.1-canary.499.60b3012.0
npm install @quenty/adorneevalue@10.5.3-canary.499.60b3012.0
npm install @quenty/animations@8.5.2-canary.499.60b3012.0
npm install @quenty/assetserviceutils@5.7.1-canary.499.60b3012.0
npm install @quenty/attributeutils@14.5.1-canary.499.60b3012.0
npm install @quenty/avatareditorutils@7.6.1-canary.499.60b3012.0
npm install @quenty/basicpane@13.5.1-canary.499.60b3012.0
npm …
```
=> fix: Rx.defaultsTo() would fire events during completion or fail, which it should not

src/actionmanager/src/Client/ActionManager.lua, src/adorneedata/src/Shared/AdorneeData.lua, src/datastore/src/Server/Modules/DataStoreStage.lua, src/settings/package.json, src/templateprovider/src/Shared/TemplateProvider.lua
<details>
<br />
```bash
npm install @quenty/actionmanager@13.10.1-canary.515.9ed6363.0
npm install @quenty/adorneedata@7.11.1-canary.515.9ed6363.0
npm install @quenty/animationprovider@11.8.1-canary.515.9ed6363.0
npm install @quenty/chatproviderservice@9.14.1-canary.515.9ed6363.0
npm install @quenty/cmdrservice@13.12.1-canary.515.9ed6363.0
npm install @quenty/datastore@13.12.1-canary.515.9ed6363.0
npm install @quenty/gameconfig@12.14.1-canary.515.9ed6363.0
npm install @quenty/gameproductservice@14.14.2-canary.515.9ed6363.0
npm install @quenty/humanoidspeed@12.12.2-canary.515.9ed6363.0
npm install @quenty/idleservice@13.13.2-canary.515.9ed6363.0
npm install …
```
=> fix: Miscellaneous fixes

src/actionmanager/src/Client/ActionManager.lua, src/actionmanager/src/Client/BaseAction.lua, src/binder/src/Shared/Binder.lua, src/binder/src/Shared/Collection/BoundChildCollection.lua, src/boundlinkutils/src/Shared/BoundLinkCollection.lua, src/datastore/README.md, src/deathreport/src/Client/DeathReportServiceClient.lua, src/ik/src/Shared/Torso/TorsoIKBase.lua, src/inputkeymaputils/src/Client/InputKeyMapListUtils.lua, src/metricutils/src/Shared/MetricUtils.lua, src/observablecollection/src/Shared/SortedList/ObservableSortedList.lua, src/radial-image/src/Client/RadialImage.story.lua, src/tie/test/modules/Server/Window.lua
<details>
<br />
```bash
npm install @quenty/actionmanager@13.12.1-canary.518.d1dc66d.0
npm install @quenty/adorneeboundingbox@8.12.1-canary.518.d1dc66d.0
npm install @quenty/animationprovider@11.10.1-canary.518.d1dc66d.0
npm install @quenty/binder@14.13.1-canary.518.d1dc66d.0
npm install @quenty/boundlinkutils@14.13.1-canary.518.d1dc66d.0
npm install @quenty/chatproviderservice@9.16.1-canary.518.d1dc66d.0
npm install @quenty/cmdrservice@13.14.1-canary.518.d1dc66d.0
npm install @quenty/colorpalette@10.13.1-canary.518.d1dc66d.0
npm install @quenty/conditions@10.14.1-canary.518.d1dc66d.0
npm install @quenty/cooldown@11.14.1-canary.518.d1dc66d.0
npm install …
```
=> feat: Sorted list improvements

src/observablecollection/src/Shared/SortedList/ObservableSortedList.lua, src/rx/src/Shared/Rx.lua, src/settings/package.json, src/table/src/Shared/Table.lua, src/templateprovider/package.json
<details>
<br />
```bash
npm install @quenty/actionmanager@13.13.1-canary.519.7414df3.0
npm install @quenty/adorneeboundingbox@8.13.1-canary.519.7414df3.0
npm install @quenty/adorneedata@7.13.1-canary.519.7414df3.0
npm install @quenty/adorneevalue@10.12.1-canary.519.7414df3.0
npm install @quenty/animationprovider@11.11.1-canary.519.7414df3.0
npm install @quenty/animations@8.12.1-canary.519.7414df3.0
npm install @quenty/assetserviceutils@5.14.1-canary.519.7414df3.0
npm install @quenty/attributeutils@14.12.1-canary.519.7414df3.0
npm install @quenty/avatareditorutils@7.13.1-canary.519.7414df3.0
npm install @quenty/basicpane@13.12.1-canary.519.7414df3.0
npm install …
```
=> fix: Fix :Observe() method in ObservableSortedList

src/buttonhighlightmodel/src/Client/HandleHighlightModel.lua, src/camera/package.json, src/camera/src/Client/Controls/GamepadRotateModel.lua, src/chatproviderservice/src/Server/Commands/ChatProviderCommandService.lua, src/chatproviderservice/src/Shared/Binders/HasChatTagsBase.lua, src/colorpalette/src/Shared/Swatch/ColorSwatch.lua, src/flipbook/src/Client/Player/FlipbookPlayer.lua, src/gameproductservice/src/Shared/Ownership/PlayerAssetOwnershipTracker.lua, src/guivisiblemanager/package.json, src/guivisiblemanager/src/Client/GuiVisibleManager.lua, src/idleservice/src/Client/IdleTargetCalculator.lua, src/ik/src/Client/Rig/IKRigClient.lua, src/ik/src/Shared/Arm/ArmIKBase.lua, src/ik/src/Shared/Resources/IKResource.lua, src/influxdbclient/src/Server/Write/InfluxDBWriteAPI.lua, src/influxdbclient/src/Server/Write/InfluxDBWriteBuffer.lua, src/inputkeymaputils/src/Shared/InputKeyMap.lua, src/observablecollection/src/Shared/SortedList/ObservableSortedList.lua, src/overriddenproperty/src/Shared/OverriddenProperty.lua, src/playerhumanoidbinder/src/Server/PlayerCharacterBinder.lua, src/playerhumanoidbinder/src/Server/PlayerHumanoidBinder.lua, src/playerinputmode/src/Client/PlayerInputModeServiceClient.lua, src/racketingropeconstraint/src/Shared/RacketingRopeConstraint.lua, src/ragdoll/src/Client/Classes/RagdollHumanoidOnFallClient.lua, src/ragdoll/src/Server/Classes/RagdollHumanoidOnFall.lua, src/ragdoll/src/Shared/Classes/BindableRagdollHumanoidOnFall.lua, src/screenshothudservice/src/Client/ScreenshotHudModel.lua, src/screenshothudservice/src/Client/ScreenshotHudServiceClient.lua, src/softshutdown/src/Client/SoftShutdownUI.lua, src/tie/src/Shared/Members/TieMemberInterface.lua
<details>
<br />
```bash
npm install @quenty/adorneeboundingbox@8.18.1-canary.531.760eab8.0
npm install @quenty/animationprovider@11.16.1-canary.531.760eab8.0
npm install @quenty/avatareditorutils@7.18.1-canary.531.760eab8.0
npm install @quenty/buttonhighlightmodel@14.16.1-canary.531.760eab8.0
npm install @quenty/camera@14.18.2-canary.531.760eab8.0
npm install @quenty/chatproviderservice@9.23.1-canary.531.760eab8.0
npm install @quenty/cmdrservice@13.20.1-canary.531.760eab8.0
npm install @quenty/colorpalette@10.19.1-canary.531.760eab8.0
npm install @quenty/conditions@10.18.1-canary.531.760eab8.0
npm install @quenty/deathreport@10.18.1-canary.531.760eab8.0
npm install …
```
=> Bulk refactors and small bug fixes

src/viewport/src/Client/ViewportControls.lua
Fixes an if statement which makes it so ViewportControls aren't disabled properly
=> fix: Incorrect if statement in ViewportControls

src/ragdoll/src/Shared/Rigging/RagdollMotorUtils.lua
This affects other people who are ragdolled, they will lag out
https://github.com/user-attachments/assets/e07305b1-3750-4381-b4b8-3c3473ef8ac9
<details>
<br />
```bash
npm install @quenty/idleservice@13.22.1-canary.523.2b7508a.0
npm install @quenty/ik@15.23.1-canary.523.2b7508a.0
npm install @quenty/ragdoll@15.22.1-canary.523.2b7508a.0
yarn add @quenty/idleservice@13.22.1-canary.523.2b7508a.0
yarn add @quenty/ik@15.23.1-canary.523.2b7508a.0
yarn add @quenty/ragdoll@15.22.1-canary.523.2b7508a.0
```
</details>
=> fix: Fix ragdolls showing issues on other people's characters

src/inputkeymaputils/src/Shared/Types/SlottedTouchButtonUtils.lua
InputKeyMapLists -requires> InputKeymap -requires> InputKeyMapUtils -requires>  SlottedTouchButtonUtils -requires> InputKeyMapLists 
creating a recursion error
=> fix: slottedtouchbutton recursion

.github/workflows/build.yml, .github/workflows/docs.yml, .github/workflows/lint-external-prs.yml, .github/workflows/lint.yml, .github/workflows/tests.yml, src/time/src/Shared/Time.lua
Make adjustments to CI/CD to allow branch protections.
=> ci: Allow branches to be protected during deploy

src/binder/package.json, src/influxdbclient/README.md, src/servicebag/src/Shared/ServiceBag.lua
Doesn't tell you the exact module, but it at least can tell you the line that invoked the yield.
=> feat: Service bag prints out where the yielding happens

src/adorneedata/package.json, src/datastore/package.json, src/datastore/src/Server/DataStore.lua, src/datastore/src/Server/PlayerDataStoreManager.lua, src/promise/src/Shared/PromiseRetryUtils.lua
This adds session locking to the DataStore system in Nevermore. You can test the session locking in here.
https://www.roblox.com/games/124775137210829/Duplication-Glitch-Testing
=> feat: Add datastore session locking system
